; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Aug 19 2021 22:26:00 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAZMSYQW4TCA:
	dc.w $0, DATAZMSYQW4TCA_1-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_2-DATAZMSYQW4TCA, DATAZMSYQW4TCA_3-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_4-DATAZMSYQW4TCA, DATAZMSYQW4TCA_5-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_6-DATAZMSYQW4TCA, DATAZMSYQW4TCA_7-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_8-DATAZMSYQW4TCA, DATAZMSYQW4TCA_9-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_A-DATAZMSYQW4TCA, DATAZMSYQW4TCA_B-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_C-DATAZMSYQW4TCA, DATAZMSYQW4TCA_D-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_E-DATAZMSYQW4TCA, DATAZMSYQW4TCA_F-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_10-DATAZMSYQW4TCA, DATAZMSYQW4TCA_11-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_12-DATAZMSYQW4TCA, DATAZMSYQW4TCA_13-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_14-DATAZMSYQW4TCA, DATAZMSYQW4TCA_15-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_16-DATAZMSYQW4TCA, DATAZMSYQW4TCA_17-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_18-DATAZMSYQW4TCA, DATAZMSYQW4TCA_19-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_1A-DATAZMSYQW4TCA, DATAZMSYQW4TCA_1B-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_1C-DATAZMSYQW4TCA, DATAZMSYQW4TCA_1D-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_1E-DATAZMSYQW4TCA, DATAZMSYQW4TCA_1F-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_20-DATAZMSYQW4TCA, DATAZMSYQW4TCA_21-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_22-DATAZMSYQW4TCA, DATAZMSYQW4TCA_23-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_24-DATAZMSYQW4TCA, DATAZMSYQW4TCA_25-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_26-DATAZMSYQW4TCA, DATAZMSYQW4TCA_27-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_28-DATAZMSYQW4TCA, DATAZMSYQW4TCA_29-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_2A-DATAZMSYQW4TCA, DATAZMSYQW4TCA_2B-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_2C-DATAZMSYQW4TCA, DATAZMSYQW4TCA_2D-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_2E-DATAZMSYQW4TCA, DATAZMSYQW4TCA_2F-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_30-DATAZMSYQW4TCA, DATAZMSYQW4TCA_31-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_32-DATAZMSYQW4TCA, DATAZMSYQW4TCA_33-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_34-DATAZMSYQW4TCA, DATAZMSYQW4TCA_35-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_36-DATAZMSYQW4TCA, DATAZMSYQW4TCA_37-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_38-DATAZMSYQW4TCA, DATAZMSYQW4TCA_39-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_3A-DATAZMSYQW4TCA, DATAZMSYQW4TCA_3B-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_3C-DATAZMSYQW4TCA, DATAZMSYQW4TCA_3D-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_3E-DATAZMSYQW4TCA, DATAZMSYQW4TCA_3F-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_40-DATAZMSYQW4TCA, DATAZMSYQW4TCA_41-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_42-DATAZMSYQW4TCA, DATAZMSYQW4TCA_43-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_44-DATAZMSYQW4TCA, DATAZMSYQW4TCA_45-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_46-DATAZMSYQW4TCA, DATAZMSYQW4TCA_47-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_48-DATAZMSYQW4TCA, DATAZMSYQW4TCA_49-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_4A-DATAZMSYQW4TCA, DATAZMSYQW4TCA_4B-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_4C-DATAZMSYQW4TCA, DATAZMSYQW4TCA_4D-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_4E-DATAZMSYQW4TCA, DATAZMSYQW4TCA_4F-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_50-DATAZMSYQW4TCA, DATAZMSYQW4TCA_51-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_52-DATAZMSYQW4TCA, DATAZMSYQW4TCA_53-DATAZMSYQW4TCA
	dc.w DATAZMSYQW4TCA_54-DATAZMSYQW4TCA, DATAZMSYQW4TCA_55-DATAZMSYQW4TCA
DATAZMSYQW4TCA_1: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $F4
DATAZMSYQW4TCA_2: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $F4
DATAZMSYQW4TCA_3: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $F4
DATAZMSYQW4TCA_4: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $F4
DATAZMSYQW4TCA_5: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $F4
DATAZMSYQW4TCA_6: dc.b $2
	dc.b $ED, $A, $0, $0, $F5
	dc.b $5, $5, $0, $9, $F5
DATAZMSYQW4TCA_7: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $F4
DATAZMSYQW4TCA_8: dc.b $2
	dc.b $E5, $B, $0, $0, $F3
	dc.b $5, $9, $0, $C, $F3
DATAZMSYQW4TCA_9: dc.b $2
	dc.b $ED, $A, $0, $0, $F5
	dc.b $5, $5, $0, $9, $F5
DATAZMSYQW4TCA_A: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $F4
DATAZMSYQW4TCA_B: dc.b $2
	dc.b $E5, $B, $0, $0, $F3
	dc.b $5, $9, $0, $C, $F3
DATAZMSYQW4TCA_C: dc.b $3
	dc.b $EC, $A, $0, $0, $EF
	dc.b $4, $C, $0, $9, $F7
	dc.b $C, $4, $0, $D, $FF
DATAZMSYQW4TCA_D: dc.b $2
	dc.b $E9, $B, $0, $0, $EC
	dc.b $1, $5, $0, $C, $4
DATAZMSYQW4TCA_E: dc.b $3
	dc.b $EA, $E, $0, $0, $E8
	dc.b $2, $C, $0, $C, $F0
	dc.b $A, $4, $0, $10, $0
DATAZMSYQW4TCA_F: dc.b $3
	dc.b $EC, $A, $0, $0, $EF
	dc.b $4, $C, $0, $9, $F7
	dc.b $C, $4, $0, $D, $FF
DATAZMSYQW4TCA_10: dc.b $2
	dc.b $E9, $B, $0, $0, $EC
	dc.b $1, $5, $0, $C, $4
DATAZMSYQW4TCA_11: dc.b $3
	dc.b $EA, $E, $0, $0, $E8
	dc.b $2, $C, $0, $C, $F0
	dc.b $A, $4, $0, $10, $0
DATAZMSYQW4TCA_12: dc.b $2
	dc.b $F3, $A, $0, $0, $ED
	dc.b $FB, $5, $0, $9, $5
DATAZMSYQW4TCA_13: dc.b $2
	dc.b $F4, $A, $0, $0, $EC
	dc.b $FC, $5, $0, $9, $4
DATAZMSYQW4TCA_14: dc.b $2
	dc.b $F4, $E, $0, $0, $E5
	dc.b $F4, $6, $0, $C, $5
DATAZMSYQW4TCA_15: dc.b $2
	dc.b $F3, $A, $0, $0, $ED
	dc.b $FB, $5, $0, $9, $5
DATAZMSYQW4TCA_16: dc.b $2
	dc.b $F4, $A, $0, $0, $EC
	dc.b $FC, $5, $0, $9, $4
DATAZMSYQW4TCA_17: dc.b $2
	dc.b $F4, $E, $0, $0, $E5
	dc.b $F4, $6, $0, $C, $5
DATAZMSYQW4TCA_18: dc.b $3
	dc.b $F8, $A, $0, $0, $EE
	dc.b $E8, $3, $0, $9, $6
	dc.b $F0, $1, $0, $D, $E
DATAZMSYQW4TCA_19: dc.b $2
	dc.b $FA, $E, $0, $0, $EC
	dc.b $EA, $5, $0, $C, $4
DATAZMSYQW4TCA_1A: dc.b $3
	dc.b $EE, $5, $0, $0, $4
	dc.b $F6, $B, $0, $4, $EC
	dc.b $FE, $1, $0, $10, $4
DATAZMSYQW4TCA_1B: dc.b $3
	dc.b $F8, $A, $0, $0, $EE
	dc.b $E8, $3, $0, $9, $6
	dc.b $F0, $1, $0, $D, $E
DATAZMSYQW4TCA_1C: dc.b $2
	dc.b $FA, $E, $0, $0, $EC
	dc.b $EA, $5, $0, $C, $4
DATAZMSYQW4TCA_1D: dc.b $3
	dc.b $EE, $5, $0, $0, $4
	dc.b $F6, $B, $0, $4, $EC
	dc.b $FE, $1, $0, $10, $4
DATAZMSYQW4TCA_1E: dc.b $3
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $F4
	dc.b $EC, $1, $0, $D, $C
DATAZMSYQW4TCA_1F: dc.b $3
	dc.b $EB, $B, $0, $0, $F0
	dc.b $B, $C, $0, $C, $F0
	dc.b $EB, $5, $0, $10, $8
DATAZMSYQW4TCA_20: dc.b $3
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $F4
	dc.b $EC, $1, $0, $D, $C
DATAZMSYQW4TCA_21: dc.b $3
	dc.b $EB, $B, $0, $0, $F0
	dc.b $B, $C, $0, $C, $F0
	dc.b $EB, $5, $0, $10, $8
DATAZMSYQW4TCA_22: dc.b $3
	dc.b $EB, $B, $0, $0, $EF
	dc.b $B, $8, $0, $C, $FF
	dc.b $3, $0, $0, $F, $7
DATAZMSYQW4TCA_23: dc.b $4
	dc.b $EF, $E, $0, $0, $E9
	dc.b $E7, $8, $0, $C, $F1
	dc.b $7, $5, $0, $F, $F9
	dc.b $FF, $4, $0, $13, $9
DATAZMSYQW4TCA_24: dc.b $3
	dc.b $EB, $B, $0, $0, $EF
	dc.b $B, $8, $0, $C, $FF
	dc.b $3, $0, $0, $F, $7
DATAZMSYQW4TCA_25: dc.b $4
	dc.b $F0, $E, $0, $0, $EA
	dc.b $E8, $8, $0, $C, $F2
	dc.b $8, $5, $0, $F, $FA
	dc.b $0, $4, $0, $13, $A
DATAZMSYQW4TCA_26: dc.b $3
	dc.b $EC, $7, $0, $0, $EC
	dc.b $F4, $2, $0, $8, $FC
	dc.b $FC, $5, $0, $B, $4
DATAZMSYQW4TCA_27: dc.b $3
	dc.b $F1, $F, $0, $0, $E9
	dc.b $E9, $0, $0, $10, $F1
	dc.b $F1, $3, $0, $11, $9
DATAZMSYQW4TCA_28: dc.b $3
	dc.b $EC, $7, $0, $0, $EC
	dc.b $F4, $2, $0, $8, $FC
	dc.b $FC, $5, $0, $B, $4
DATAZMSYQW4TCA_29: dc.b $3
	dc.b $F1, $F, $0, $0, $E9
	dc.b $E9, $0, $0, $10, $F1
	dc.b $F1, $3, $0, $11, $9
DATAZMSYQW4TCA_2A: dc.b $3
	dc.b $EB, $2, $0, $0, $B
	dc.b $F3, $3, $0, $3, $3
	dc.b $FB, $A, $0, $7, $EB
DATAZMSYQW4TCA_2B: dc.b $4
	dc.b $F8, $E, $0, $0, $E7
	dc.b $10, $8, $0, $C, $EF
	dc.b $E8, $1, $0, $F, $FF
	dc.b $F8, $5, $0, $11, $7
DATAZMSYQW4TCA_2C: dc.b $3
	dc.b $EB, $2, $0, $0, $B
	dc.b $F3, $3, $0, $3, $3
	dc.b $FB, $A, $0, $7, $EB
DATAZMSYQW4TCA_2D: dc.b $4
	dc.b $F8, $E, $0, $0, $E7
	dc.b $10, $8, $0, $C, $EF
	dc.b $E8, $1, $0, $F, $FF
	dc.b $F8, $5, $0, $11, $7
DATAZMSYQW4TCA_2E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAZMSYQW4TCA_2F: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAZMSYQW4TCA_30: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAZMSYQW4TCA_31: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAZMSYQW4TCA_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAZMSYQW4TCA_33: dc.b $2
	dc.b $F5, $E, $0, $0, $EC
	dc.b $F5, $2, $0, $C, $C
DATAZMSYQW4TCA_34: dc.b $3
	dc.b $F8, $A, $0, $0, $F0
	dc.b $F0, $8, $0, $9, $F8
	dc.b $F8, $1, $0, $C, $8
DATAZMSYQW4TCA_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
DATAZMSYQW4TCA_36: dc.b $3
	dc.b $F0, $A, $0, $0, $F0
	dc.b $8, $8, $0, $9, $F8
	dc.b $F8, $1, $0, $C, $8
DATAZMSYQW4TCA_37: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $5, $0, $C, $F8
DATAZMSYQW4TCA_38: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $5, $0, $C, $F8
DATAZMSYQW4TCA_39: dc.b $1
	dc.b $FC, $A, $0, $0, $F9
DATAZMSYQW4TCA_3A: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $5, $0, $C, $F8
DATAZMSYQW4TCA_3B: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $5, $0, $C, $F8
DATAZMSYQW4TCA_3C: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $5, $0, $C, $F8
DATAZMSYQW4TCA_3D: dc.b $2
	dc.b $EC, $E, $0, $0, $EF
	dc.b $4, $5, $0, $C, $F7
DATAZMSYQW4TCA_3E: dc.b $2
	dc.b $EC, $E, $0, $0, $EF
	dc.b $4, $5, $0, $C, $F7
DATAZMSYQW4TCA_3F: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $5, $0, $C, $F8
DATAZMSYQW4TCA_40: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $8, $0, $C, $F6
	dc.b $E3, $4, $0, $F, $FE
DATAZMSYQW4TCA_41: dc.b $2
	dc.b $F2, $F, $0, $0, $E3
	dc.b $F2, $5, $0, $10, $3
DATAZMSYQW4TCA_42: dc.b $3
	dc.b $F2, $E, $0, $0, $E4
	dc.b $A, $0, $0, $C, $F4
	dc.b $FA, $5, $0, $D, $4
DATAZMSYQW4TCA_43: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $8, $0, $C, $F6
	dc.b $E3, $4, $0, $F, $FE
DATAZMSYQW4TCA_44: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $8, $0, $C, $F6
	dc.b $E3, $4, $0, $F, $FE
DATAZMSYQW4TCA_45: dc.b $2
	dc.b $F9, $F, $8, $0, $ED
	dc.b $F9, $5, $8, $10, $DD
DATAZMSYQW4TCA_46: dc.b $3
	dc.b $F8, $E, $8, $0, $EB
	dc.b $10, $0, $8, $C, $F3
	dc.b $0, $5, $8, $D, $DB
DATAZMSYQW4TCA_47: dc.b $2
	dc.b $EC, $E, $0, $0, $EF
	dc.b $4, $5, $0, $C, $F7
DATAZMSYQW4TCA_48: dc.b $2
	dc.b $EC, $E, $0, $0, $EF
	dc.b $4, $5, $0, $C, $F7
DATAZMSYQW4TCA_49: dc.b $2
	dc.b $EC, $E, $0, $0, $EF
	dc.b $4, $5, $0, $C, $F7
DATAZMSYQW4TCA_4A: dc.b $2
	dc.b $EC, $E, $0, $0, $EF
	dc.b $4, $5, $0, $C, $F7
DATAZMSYQW4TCA_4B: dc.b $2
	dc.b $EC, $E, $0, $0, $EF
	dc.b $4, $5, $0, $C, $F7
DATAZMSYQW4TCA_4C: dc.b $2
	dc.b $EC, $E, $0, $0, $EF
	dc.b $4, $5, $0, $C, $F7
DATAZMSYQW4TCA_4D: dc.b $2
	dc.b $F0, $B, $0, $0, $EC
	dc.b $F8, $5, $0, $C, $4
DATAZMSYQW4TCA_4E: dc.b $2
	dc.b $FC, $E, $10, $0, $EF
	dc.b $EC, $5, $10, $C, $F7
DATAZMSYQW4TCA_4F: dc.b $2
	dc.b $F0, $B, $8, $0, $FC
	dc.b $F8, $5, $8, $C, $EC
DATAZMSYQW4TCA_50: dc.b $2
	dc.b $EC, $E, $0, $0, $EF
	dc.b $4, $5, $0, $C, $F7
DATAZMSYQW4TCA_51: dc.b $2
	dc.b $EC, $E, $8, $0, $F1
	dc.b $4, $5, $8, $C, $F9
DATAZMSYQW4TCA_52: dc.b $2
	dc.b $EC, $E, $0, $0, $EF
	dc.b $4, $5, $0, $C, $F7
DATAZMSYQW4TCA_53: dc.b $3
	dc.b $ED, $B, $0, $0, $EC
	dc.b $F5, $3, $0, $C, $4
	dc.b $5, $1, $0, $10, $C
DATAZMSYQW4TCA_54: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $5, $0, $C, $F8
DATAZMSYQW4TCA_55: dc.b $3
	dc.b $ED, $B, $0, $0, $EC
	dc.b $F5, $3, $0, $C, $4
	dc.b $5, $1, $0, $10, $C
	even