; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Aug 14 2021 18:24:20 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAMD7G8PFY8C9:
	dc.w $0, DATAMD7G8PFY8C9_1-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_2-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_3-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_4-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_5-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_6-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_7-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_8-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_9-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_A-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_B-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_C-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_D-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_E-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_F-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_10-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_11-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_12-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_13-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_14-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_15-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_16-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_17-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_18-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_19-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_1A-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_1B-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_1C-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_1D-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_1E-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_1F-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_20-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_21-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_22-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_23-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_24-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_25-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_26-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_27-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_28-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_29-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_2A-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_2B-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_2C-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_2D-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_2E-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_2F-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_30-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_31-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_32-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_33-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_34-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_35-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_36-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_37-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_38-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_39-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_3A-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_3B-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_3C-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_3D-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_3E-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_3F-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_40-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_41-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_42-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_43-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_44-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_45-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_46-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_47-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_48-DATAMD7G8PFY8C9, $0
	dc.w $0, $0
	dc.w DATAMD7G8PFY8C9_4C-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_4D-DATAMD7G8PFY8C9
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATAMD7G8PFY8C9_53-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_54-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_55-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_56-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_57-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_58-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_59-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_5A-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_5B-DATAMD7G8PFY8C9
	dc.w DATAMD7G8PFY8C9_5C-DATAMD7G8PFY8C9, DATAMD7G8PFY8C9_5D-DATAMD7G8PFY8C9
DATAMD7G8PFY8C9_1: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAMD7G8PFY8C9_2: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAMD7G8PFY8C9_3: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAMD7G8PFY8C9_4: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAMD7G8PFY8C9_5: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAMD7G8PFY8C9_6: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $4, $0, $C, $F6
DATAMD7G8PFY8C9_7: dc.b $2
	dc.b $ED, $A, $0, $0, $F6
	dc.b $5, $5, $0, $9, $F6
DATAMD7G8PFY8C9_8: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $1, $0, $C, $F6
	dc.b $B, $4, $0, $E, $6
DATAMD7G8PFY8C9_9: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $4, $0, $C, $F6
DATAMD7G8PFY8C9_A: dc.b $2
	dc.b $ED, $A, $0, $0, $F6
	dc.b $5, $5, $0, $9, $F6
DATAMD7G8PFY8C9_B: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $1, $0, $C, $F6
	dc.b $B, $4, $0, $E, $6
DATAMD7G8PFY8C9_C: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $8, $0, $C, $FC
	dc.b $D, $0, $0, $F, $FC
DATAMD7G8PFY8C9_D: dc.b $3
	dc.b $ED, $A, $0, $0, $EE
	dc.b $FD, $2, $0, $9, $6
	dc.b $5, $0, $0, $C, $FE
DATAMD7G8PFY8C9_E: dc.b $3
	dc.b $E6, $B, $0, $0, $ED
	dc.b $6, $5, $0, $C, $FD
	dc.b $F6, $5, $0, $10, $5
DATAMD7G8PFY8C9_F: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $8, $0, $C, $FC
	dc.b $D, $0, $0, $F, $FC
DATAMD7G8PFY8C9_10: dc.b $3
	dc.b $ED, $A, $0, $0, $EE
	dc.b $FD, $2, $0, $9, $6
	dc.b $5, $0, $0, $C, $FE
DATAMD7G8PFY8C9_11: dc.b $3
	dc.b $E6, $B, $0, $0, $ED
	dc.b $6, $5, $0, $C, $FD
	dc.b $F6, $5, $0, $10, $5
DATAMD7G8PFY8C9_12: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $FC, $1, $0, $C, $10
DATAMD7G8PFY8C9_13: dc.b $2
	dc.b $F3, $A, $0, $0, $EF
	dc.b $FB, $5, $0, $9, $7
DATAMD7G8PFY8C9_14: dc.b $2
	dc.b $ED, $7, $0, $0, $6
	dc.b $F5, $A, $0, $8, $EE
DATAMD7G8PFY8C9_15: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $FC, $1, $0, $C, $10
DATAMD7G8PFY8C9_16: dc.b $2
	dc.b $F3, $A, $0, $0, $EF
	dc.b $FB, $5, $0, $9, $7
DATAMD7G8PFY8C9_17: dc.b $2
	dc.b $ED, $7, $0, $0, $6
	dc.b $F5, $A, $0, $8, $EE
DATAMD7G8PFY8C9_18: dc.b $3
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $2, $0, $C, $4
	dc.b $FC, $0, $0, $F, $C
DATAMD7G8PFY8C9_19: dc.b $3
	dc.b $FA, $A, $0, $0, $EB
	dc.b $F2, $8, $0, $9, $FB
	dc.b $FA, $0, $0, $C, $3
DATAMD7G8PFY8C9_1A: dc.b $3
	dc.b $FB, $E, $0, $0, $E5
	dc.b $EB, $5, $0, $C, $F5
	dc.b $F3, $5, $0, $10, $5
DATAMD7G8PFY8C9_1B: dc.b $3
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $2, $0, $C, $4
	dc.b $FC, $0, $0, $F, $C
DATAMD7G8PFY8C9_1C: dc.b $3
	dc.b $FA, $A, $0, $0, $EB
	dc.b $F2, $8, $0, $9, $FB
	dc.b $FA, $0, $0, $C, $3
DATAMD7G8PFY8C9_1D: dc.b $3
	dc.b $FB, $E, $0, $0, $E5
	dc.b $EB, $5, $0, $C, $F5
	dc.b $F3, $5, $0, $10, $5
DATAMD7G8PFY8C9_1E: dc.b $3
	dc.b $ED, $B, $0, $0, $F7
	dc.b $5, $1, $0, $C, $EF
	dc.b $D, $0, $0, $E, $7
DATAMD7G8PFY8C9_1F: dc.b $2
	dc.b $EC, $A, $0, $0, $F8
	dc.b $4, $5, $0, $9, $F8
DATAMD7G8PFY8C9_20: dc.b $3
	dc.b $ED, $B, $0, $0, $F7
	dc.b $5, $1, $0, $C, $EF
	dc.b $D, $0, $0, $E, $7
DATAMD7G8PFY8C9_21: dc.b $2
	dc.b $EC, $A, $0, $0, $F8
	dc.b $4, $5, $0, $9, $F8
DATAMD7G8PFY8C9_22: dc.b $3
	dc.b $EE, $A, $0, $0, $EA
	dc.b $FE, $9, $0, $9, $2
	dc.b $6, $2, $0, $F, $FA
DATAMD7G8PFY8C9_23: dc.b $3
	dc.b $E9, $A, $0, $0, $ED
	dc.b $1, $C, $0, $9, $F5
	dc.b $9, $4, $0, $D, $5
DATAMD7G8PFY8C9_24: dc.b $3
	dc.b $EE, $A, $0, $0, $EA
	dc.b $FE, $9, $0, $9, $2
	dc.b $6, $2, $0, $F, $FA
DATAMD7G8PFY8C9_25: dc.b $3
	dc.b $E9, $A, $0, $0, $ED
	dc.b $1, $C, $0, $9, $F5
	dc.b $9, $4, $0, $D, $5
DATAMD7G8PFY8C9_26: dc.b $3
	dc.b $F0, $E, $0, $0, $EE
	dc.b $8, $4, $0, $C, $6
	dc.b $F0, $0, $0, $E, $E
DATAMD7G8PFY8C9_27: dc.b $2
	dc.b $EF, $A, $0, $0, $ED
	dc.b $F7, $5, $0, $9, $5
DATAMD7G8PFY8C9_28: dc.b $3
	dc.b $F0, $E, $0, $0, $ED
	dc.b $8, $4, $0, $C, $5
	dc.b $F0, $0, $0, $E, $D
DATAMD7G8PFY8C9_29: dc.b $2
	dc.b $EF, $A, $0, $0, $EC
	dc.b $F7, $5, $0, $9, $4
DATAMD7G8PFY8C9_2A: dc.b $3
	dc.b $1, $A, $0, $0, $E9
	dc.b $E9, $6, $0, $9, $F9
	dc.b $1, $8, $0, $F, $1
DATAMD7G8PFY8C9_2B: dc.b $3
	dc.b $0, $A, $0, $0, $E4
	dc.b $F0, $5, $0, $9, $FC
	dc.b $0, $1, $0, $D, $FC
DATAMD7G8PFY8C9_2C: dc.b $3
	dc.b $1, $A, $0, $0, $E9
	dc.b $E9, $6, $0, $9, $F9
	dc.b $1, $8, $0, $F, $1
DATAMD7G8PFY8C9_2D: dc.b $3
	dc.b $0, $A, $0, $0, $E3
	dc.b $F0, $5, $0, $9, $FB
	dc.b $0, $1, $0, $D, $FB
DATAMD7G8PFY8C9_2E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAMD7G8PFY8C9_2F: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAMD7G8PFY8C9_30: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAMD7G8PFY8C9_31: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAMD7G8PFY8C9_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAMD7G8PFY8C9_33: dc.b $1
	dc.b $F6, $F, $0, $0, $F2
DATAMD7G8PFY8C9_34: dc.b $1
	dc.b $F6, $F, $0, $0, $F1
DATAMD7G8PFY8C9_35: dc.b $1
	dc.b $F6, $F, $0, $0, $F2
DATAMD7G8PFY8C9_36: dc.b $1
	dc.b $F6, $F, $0, $0, $F1
DATAMD7G8PFY8C9_37: dc.b $2
	dc.b $ED, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F4
DATAMD7G8PFY8C9_38: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAMD7G8PFY8C9_39: dc.b $1
	dc.b $F9, $B, $0, $0, $F4
DATAMD7G8PFY8C9_3A: dc.b $2
	dc.b $EC, $B, $0, $0, $EE
	dc.b $C, $8, $0, $C, $EE
DATAMD7G8PFY8C9_3B: dc.b $2
	dc.b $ED, $B, $0, $0, $EB
	dc.b $D, $8, $0, $C, $EB
DATAMD7G8PFY8C9_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $0
	dc.b $FC, $8, $0, $9, $E8
DATAMD7G8PFY8C9_3D: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAMD7G8PFY8C9_3E: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAMD7G8PFY8C9_3F: dc.b $2
	dc.b $F4, $A, $0, $0, $0
	dc.b $FC, $8, $0, $9, $E8
DATAMD7G8PFY8C9_40: dc.b $4
	dc.b $10, $4, $0, $0, $EC
	dc.b $F0, $B, $0, $2, $F4
	dc.b $E8, $4, $0, $E, $FC
	dc.b $10, $0, $0, $10, $4
DATAMD7G8PFY8C9_41: dc.b $3
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $2, $0, $9, $E4
	dc.b $F8, $9, $0, $C, $4
DATAMD7G8PFY8C9_42: dc.b $3
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $2, $0, $9, $E4
	dc.b $F8, $9, $0, $C, $4
DATAMD7G8PFY8C9_43: dc.b $4
	dc.b $10, $4, $0, $0, $F0
	dc.b $F0, $B, $0, $2, $F8
	dc.b $E8, $4, $0, $E, $0
	dc.b $10, $0, $0, $10, $8
DATAMD7G8PFY8C9_44: dc.b $4
	dc.b $10, $4, $0, $0, $F0
	dc.b $F0, $B, $0, $2, $F8
	dc.b $E8, $4, $0, $E, $0
	dc.b $10, $0, $0, $10, $8
DATAMD7G8PFY8C9_45: dc.b $3
	dc.b $ED, $B, $0, $0, $ED
	dc.b $C, $4, $0, $C, $F5
	dc.b $FD, $1, $0, $E, $5
DATAMD7G8PFY8C9_46: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F8
	dc.b $FC, $1, $0, $D, $8
DATAMD7G8PFY8C9_47: dc.b $3
	dc.b $ED, $B, $0, $0, $ED
	dc.b $C, $4, $0, $C, $F5
	dc.b $FD, $1, $0, $E, $5
DATAMD7G8PFY8C9_48: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F8
	dc.b $FC, $1, $0, $D, $8
DATAMD7G8PFY8C9_4C: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATAMD7G8PFY8C9_4D: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATAMD7G8PFY8C9_53: dc.b $2
	dc.b $F4, $A, $8, $0, $E8
	dc.b $FC, $8, $8, $9, $0
DATAMD7G8PFY8C9_54: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAMD7G8PFY8C9_55: dc.b $3
	dc.b $EC, $F, $0, $0, $F2
	dc.b $FC, $0, $0, $10, $EA
	dc.b $C, $8, $0, $11, $FA
DATAMD7G8PFY8C9_56: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $F4, $1, $0, $E, $C
	dc.b $C, $C, $0, $10, $EC
DATAMD7G8PFY8C9_57: dc.b $4
	dc.b $EE, $B, $0, $0, $F4
	dc.b $F6, $1, $0, $C, $EC
	dc.b $F6, $2, $0, $E, $C
	dc.b $E, $4, $0, $11, $FC
DATAMD7G8PFY8C9_58: dc.b $4
	dc.b $F0, $D, $0, $0, $EC
	dc.b $E8, $4, $0, $8, $F4
	dc.b $0, $A, $0, $A, $F4
	dc.b $F0, $1, $0, $13, $C
DATAMD7G8PFY8C9_59: dc.b $4
	dc.b $EE, $F, $0, $0, $F4
	dc.b $FE, $1, $0, $10, $14
	dc.b $6, $0, $0, $12, $EC
	dc.b $E, $1, $0, $13, $F4
DATAMD7G8PFY8C9_5A: dc.b $4
	dc.b $F5, $C, $0, $0, $E4
	dc.b $ED, $0, $0, $4, $F4
	dc.b $FD, $E, $0, $5, $F4
	dc.b $15, $4, $0, $11, $F4
DATAMD7G8PFY8C9_5B: dc.b $4
	dc.b $7, $D, $0, $0, $EC
	dc.b $EF, $A, $0, $8, $F4
	dc.b $17, $4, $0, $11, $FC
	dc.b $7, $1, $0, $13, $C
DATAMD7G8PFY8C9_5C: dc.b $4
	dc.b $F8, $F, $0, $0, $EC
	dc.b $E8, $1, $0, $10, $4
	dc.b $F8, $4, $0, $12, $C
	dc.b $0, $0, $0, $14, $C
DATAMD7G8PFY8C9_5D: dc.b $4
	dc.b $F0, $E, $0, $0, $ED
	dc.b $E8, $4, $0, $C, $FD
	dc.b $8, $C, $0, $E, $FD
	dc.b $10, $0, $0, $12, $5
	even