; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Aug 19 2021 12:40:50 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAUOU4MK15AE:
	dc.w $0, DATAUOU4MK15AE_1-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_2-DATAUOU4MK15AE, DATAUOU4MK15AE_3-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_4-DATAUOU4MK15AE, DATAUOU4MK15AE_5-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_6-DATAUOU4MK15AE, DATAUOU4MK15AE_7-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_8-DATAUOU4MK15AE, DATAUOU4MK15AE_9-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_A-DATAUOU4MK15AE, DATAUOU4MK15AE_B-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_C-DATAUOU4MK15AE, DATAUOU4MK15AE_D-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_E-DATAUOU4MK15AE, DATAUOU4MK15AE_F-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_10-DATAUOU4MK15AE, DATAUOU4MK15AE_11-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_12-DATAUOU4MK15AE, DATAUOU4MK15AE_13-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_14-DATAUOU4MK15AE, DATAUOU4MK15AE_15-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_16-DATAUOU4MK15AE, DATAUOU4MK15AE_17-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_18-DATAUOU4MK15AE, DATAUOU4MK15AE_19-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_1A-DATAUOU4MK15AE, DATAUOU4MK15AE_1B-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_1C-DATAUOU4MK15AE, DATAUOU4MK15AE_1D-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_1E-DATAUOU4MK15AE, DATAUOU4MK15AE_1F-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_20-DATAUOU4MK15AE, DATAUOU4MK15AE_21-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_22-DATAUOU4MK15AE, DATAUOU4MK15AE_23-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_24-DATAUOU4MK15AE, DATAUOU4MK15AE_25-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_26-DATAUOU4MK15AE, DATAUOU4MK15AE_27-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_28-DATAUOU4MK15AE, DATAUOU4MK15AE_29-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_2A-DATAUOU4MK15AE, DATAUOU4MK15AE_2B-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_2C-DATAUOU4MK15AE, DATAUOU4MK15AE_2D-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_2E-DATAUOU4MK15AE, DATAUOU4MK15AE_2F-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_30-DATAUOU4MK15AE, DATAUOU4MK15AE_31-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_32-DATAUOU4MK15AE, DATAUOU4MK15AE_33-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_34-DATAUOU4MK15AE, DATAUOU4MK15AE_35-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_36-DATAUOU4MK15AE, DATAUOU4MK15AE_37-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_38-DATAUOU4MK15AE, DATAUOU4MK15AE_39-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_3A-DATAUOU4MK15AE, DATAUOU4MK15AE_3B-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_3C-DATAUOU4MK15AE, DATAUOU4MK15AE_3D-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_3E-DATAUOU4MK15AE, DATAUOU4MK15AE_3F-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_40-DATAUOU4MK15AE, DATAUOU4MK15AE_41-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_42-DATAUOU4MK15AE, DATAUOU4MK15AE_43-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_44-DATAUOU4MK15AE, DATAUOU4MK15AE_45-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_46-DATAUOU4MK15AE, DATAUOU4MK15AE_47-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_48-DATAUOU4MK15AE, $0
	dc.w $0, $0
	dc.w DATAUOU4MK15AE_4C-DATAUOU4MK15AE, DATAUOU4MK15AE_4D-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_4E-DATAUOU4MK15AE, DATAUOU4MK15AE_4F-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_50-DATAUOU4MK15AE, DATAUOU4MK15AE_51-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_52-DATAUOU4MK15AE, DATAUOU4MK15AE_53-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_54-DATAUOU4MK15AE, DATAUOU4MK15AE_55-DATAUOU4MK15AE
	dc.w DATAUOU4MK15AE_56-DATAUOU4MK15AE, DATAUOU4MK15AE_57-DATAUOU4MK15AE
DATAUOU4MK15AE_1: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAUOU4MK15AE_2: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAUOU4MK15AE_3: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAUOU4MK15AE_4: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAUOU4MK15AE_5: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAUOU4MK15AE_6: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $4, $0, $C, $F6
DATAUOU4MK15AE_7: dc.b $2
	dc.b $ED, $A, $0, $0, $F6
	dc.b $5, $5, $0, $9, $F6
DATAUOU4MK15AE_8: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $1, $0, $C, $F6
	dc.b $B, $4, $0, $E, $6
DATAUOU4MK15AE_9: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $4, $0, $C, $F6
DATAUOU4MK15AE_A: dc.b $2
	dc.b $ED, $A, $0, $0, $F6
	dc.b $5, $5, $0, $9, $F6
DATAUOU4MK15AE_B: dc.b $3
	dc.b $EB, $B, $0, $0, $F6
	dc.b $B, $1, $0, $C, $F6
	dc.b $B, $4, $0, $E, $6
DATAUOU4MK15AE_C: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $8, $0, $C, $FC
	dc.b $D, $0, $0, $F, $FC
DATAUOU4MK15AE_D: dc.b $3
	dc.b $ED, $A, $0, $0, $EE
	dc.b $FD, $2, $0, $9, $6
	dc.b $5, $0, $0, $C, $FE
DATAUOU4MK15AE_E: dc.b $3
	dc.b $E6, $B, $0, $0, $ED
	dc.b $6, $5, $0, $C, $FD
	dc.b $F6, $5, $0, $10, $5
DATAUOU4MK15AE_F: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $8, $0, $C, $FC
	dc.b $D, $0, $0, $F, $FC
DATAUOU4MK15AE_10: dc.b $3
	dc.b $ED, $A, $0, $0, $EE
	dc.b $FD, $2, $0, $9, $6
	dc.b $5, $0, $0, $C, $FE
DATAUOU4MK15AE_11: dc.b $3
	dc.b $E6, $B, $0, $0, $ED
	dc.b $6, $5, $0, $C, $FD
	dc.b $F6, $5, $0, $10, $5
DATAUOU4MK15AE_12: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $FC, $1, $0, $C, $10
DATAUOU4MK15AE_13: dc.b $2
	dc.b $F3, $A, $0, $0, $EF
	dc.b $FB, $5, $0, $9, $7
DATAUOU4MK15AE_14: dc.b $2
	dc.b $ED, $7, $0, $0, $6
	dc.b $F5, $A, $0, $8, $EE
DATAUOU4MK15AE_15: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $FC, $1, $0, $C, $10
DATAUOU4MK15AE_16: dc.b $2
	dc.b $F3, $A, $0, $0, $EF
	dc.b $FB, $5, $0, $9, $7
DATAUOU4MK15AE_17: dc.b $2
	dc.b $ED, $7, $0, $0, $6
	dc.b $F5, $A, $0, $8, $EE
DATAUOU4MK15AE_18: dc.b $3
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $2, $0, $C, $4
	dc.b $FC, $0, $0, $F, $C
DATAUOU4MK15AE_19: dc.b $3
	dc.b $FA, $A, $0, $0, $EB
	dc.b $F2, $8, $0, $9, $FB
	dc.b $FA, $0, $0, $C, $3
DATAUOU4MK15AE_1A: dc.b $3
	dc.b $FB, $E, $0, $0, $E5
	dc.b $EB, $5, $0, $C, $F5
	dc.b $F3, $5, $0, $10, $5
DATAUOU4MK15AE_1B: dc.b $3
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $2, $0, $C, $4
	dc.b $FC, $0, $0, $F, $C
DATAUOU4MK15AE_1C: dc.b $3
	dc.b $FA, $A, $0, $0, $EB
	dc.b $F2, $8, $0, $9, $FB
	dc.b $FA, $0, $0, $C, $3
DATAUOU4MK15AE_1D: dc.b $3
	dc.b $FB, $E, $0, $0, $E5
	dc.b $EB, $5, $0, $C, $F5
	dc.b $F3, $5, $0, $10, $5
DATAUOU4MK15AE_1E: dc.b $3
	dc.b $ED, $B, $0, $0, $F7
	dc.b $5, $1, $0, $C, $EF
	dc.b $D, $0, $0, $E, $7
DATAUOU4MK15AE_1F: dc.b $2
	dc.b $EC, $A, $0, $0, $F8
	dc.b $4, $5, $0, $9, $F8
DATAUOU4MK15AE_20: dc.b $3
	dc.b $ED, $B, $0, $0, $F7
	dc.b $5, $1, $0, $C, $EF
	dc.b $D, $0, $0, $E, $7
DATAUOU4MK15AE_21: dc.b $2
	dc.b $EC, $A, $0, $0, $F8
	dc.b $4, $5, $0, $9, $F8
DATAUOU4MK15AE_22: dc.b $3
	dc.b $EE, $A, $0, $0, $EA
	dc.b $FE, $9, $0, $9, $2
	dc.b $6, $2, $0, $F, $FA
DATAUOU4MK15AE_23: dc.b $3
	dc.b $E9, $A, $0, $0, $ED
	dc.b $1, $C, $0, $9, $F5
	dc.b $9, $4, $0, $D, $5
DATAUOU4MK15AE_24: dc.b $3
	dc.b $EE, $A, $0, $0, $EA
	dc.b $FE, $9, $0, $9, $2
	dc.b $6, $2, $0, $F, $FA
DATAUOU4MK15AE_25: dc.b $3
	dc.b $E9, $A, $0, $0, $ED
	dc.b $1, $C, $0, $9, $F5
	dc.b $9, $4, $0, $D, $5
DATAUOU4MK15AE_26: dc.b $3
	dc.b $F0, $E, $0, $0, $EE
	dc.b $8, $4, $0, $C, $6
	dc.b $F0, $0, $0, $E, $E
DATAUOU4MK15AE_27: dc.b $2
	dc.b $EF, $A, $0, $0, $ED
	dc.b $F7, $5, $0, $9, $5
DATAUOU4MK15AE_28: dc.b $3
	dc.b $F0, $E, $0, $0, $ED
	dc.b $8, $4, $0, $C, $5
	dc.b $F0, $0, $0, $E, $D
DATAUOU4MK15AE_29: dc.b $2
	dc.b $EF, $A, $0, $0, $EC
	dc.b $F7, $5, $0, $9, $4
DATAUOU4MK15AE_2A: dc.b $3
	dc.b $1, $A, $0, $0, $E9
	dc.b $E9, $6, $0, $9, $F9
	dc.b $1, $8, $0, $F, $1
DATAUOU4MK15AE_2B: dc.b $3
	dc.b $0, $A, $0, $0, $E4
	dc.b $F0, $5, $0, $9, $FC
	dc.b $0, $1, $0, $D, $FC
DATAUOU4MK15AE_2C: dc.b $3
	dc.b $1, $A, $0, $0, $E9
	dc.b $E9, $6, $0, $9, $F9
	dc.b $1, $8, $0, $F, $1
DATAUOU4MK15AE_2D: dc.b $3
	dc.b $0, $A, $0, $0, $E3
	dc.b $F0, $5, $0, $9, $FB
	dc.b $0, $1, $0, $D, $FB
DATAUOU4MK15AE_2E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAUOU4MK15AE_2F: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAUOU4MK15AE_30: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAUOU4MK15AE_31: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAUOU4MK15AE_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAUOU4MK15AE_33: dc.b $1
	dc.b $F6, $F, $0, $0, $F2
DATAUOU4MK15AE_34: dc.b $1
	dc.b $F6, $F, $0, $0, $F2
DATAUOU4MK15AE_35: dc.b $1
	dc.b $F6, $F, $0, $0, $F2
DATAUOU4MK15AE_36: dc.b $1
	dc.b $F6, $F, $0, $0, $F2
DATAUOU4MK15AE_37: dc.b $2
	dc.b $ED, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F4
DATAUOU4MK15AE_38: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAUOU4MK15AE_39: dc.b $1
	dc.b $F9, $B, $0, $0, $F4
DATAUOU4MK15AE_3A: dc.b $2
	dc.b $EC, $B, $0, $0, $EE
	dc.b $C, $8, $0, $C, $EE
DATAUOU4MK15AE_3B: dc.b $2
	dc.b $ED, $B, $0, $0, $EB
	dc.b $D, $8, $0, $C, $EB
DATAUOU4MK15AE_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $0
	dc.b $FC, $8, $0, $9, $E8
DATAUOU4MK15AE_3D: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAUOU4MK15AE_3E: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAUOU4MK15AE_3F: dc.b $2
	dc.b $F4, $A, $0, $0, $0
	dc.b $FC, $8, $0, $9, $E8
DATAUOU4MK15AE_40: dc.b $4
	dc.b $10, $4, $0, $0, $EC
	dc.b $F0, $B, $0, $2, $F4
	dc.b $E8, $4, $0, $E, $FC
	dc.b $10, $0, $0, $10, $4
DATAUOU4MK15AE_41: dc.b $3
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $2, $0, $9, $E4
	dc.b $F8, $9, $0, $C, $4
DATAUOU4MK15AE_42: dc.b $3
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $2, $0, $9, $E4
	dc.b $F8, $9, $0, $C, $4
DATAUOU4MK15AE_43: dc.b $4
	dc.b $10, $4, $0, $0, $F0
	dc.b $F0, $B, $0, $2, $F8
	dc.b $E8, $4, $0, $E, $0
	dc.b $10, $0, $0, $10, $8
DATAUOU4MK15AE_44: dc.b $4
	dc.b $10, $4, $0, $0, $F0
	dc.b $F0, $B, $0, $2, $F8
	dc.b $E8, $4, $0, $E, $0
	dc.b $10, $0, $0, $10, $8
DATAUOU4MK15AE_45: dc.b $3
	dc.b $ED, $B, $0, $0, $ED
	dc.b $C, $4, $0, $C, $F5
	dc.b $FD, $1, $0, $E, $5
DATAUOU4MK15AE_46: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F8
	dc.b $FC, $1, $0, $D, $8
DATAUOU4MK15AE_47: dc.b $3
	dc.b $ED, $B, $0, $0, $ED
	dc.b $C, $4, $0, $C, $F5
	dc.b $FD, $1, $0, $E, $5
DATAUOU4MK15AE_48: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F8
	dc.b $FC, $1, $0, $D, $8
DATAUOU4MK15AE_4C: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATAUOU4MK15AE_4D: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATAUOU4MK15AE_4E: dc.b $4
	dc.b $EC, $D, $0, $0, $EC
	dc.b $E4, $4, $0, $8, $F4
	dc.b $FC, $A, $0, $A, $F4
	dc.b $EC, $1, $0, $13, $C
DATAUOU4MK15AE_4F: dc.b $2
	dc.b $F0, $D, $0, $0, $F0
	dc.b $0, $5, $0, $8, $F8
DATAUOU4MK15AE_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAUOU4MK15AE_51: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAUOU4MK15AE_52: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATAUOU4MK15AE_53: dc.b $2
	dc.b $F4, $A, $8, $0, $E8
	dc.b $FC, $8, $8, $9, $0
DATAUOU4MK15AE_54: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAUOU4MK15AE_55: dc.b $3
	dc.b $EC, $F, $0, $0, $F2
	dc.b $FC, $0, $0, $10, $EA
	dc.b $C, $8, $0, $11, $FA
DATAUOU4MK15AE_56: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $F4, $1, $0, $E, $C
	dc.b $C, $C, $0, $10, $EC
DATAUOU4MK15AE_57: dc.b $4
	dc.b $EE, $B, $0, $0, $F4
	dc.b $F6, $1, $0, $C, $EC
	dc.b $F6, $2, $0, $E, $C
	dc.b $E, $4, $0, $11, $FC
	even