; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Aug 23 2021 20:31:33 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAEUYQ23E4E2V:
	dc.w DATAEUYQ23E4E2V_0-DATAEUYQ23E4E2V, DATAEUYQ23E4E2V_1-DATAEUYQ23E4E2V
	dc.w DATAEUYQ23E4E2V_2-DATAEUYQ23E4E2V, DATAEUYQ23E4E2V_3-DATAEUYQ23E4E2V
	dc.w DATAEUYQ23E4E2V_4-DATAEUYQ23E4E2V, DATAEUYQ23E4E2V_5-DATAEUYQ23E4E2V
	dc.w DATAEUYQ23E4E2V_6-DATAEUYQ23E4E2V, DATAEUYQ23E4E2V_7-DATAEUYQ23E4E2V
	dc.w DATAEUYQ23E4E2V_8-DATAEUYQ23E4E2V, DATAEUYQ23E4E2V_9-DATAEUYQ23E4E2V
	dc.w DATAEUYQ23E4E2V_A-DATAEUYQ23E4E2V, DATAEUYQ23E4E2V_B-DATAEUYQ23E4E2V
	dc.w DATAEUYQ23E4E2V_C-DATAEUYQ23E4E2V
DATAEUYQ23E4E2V_0: dc.b $7
	dc.b $EC, $1, $0, $A, $E4
	dc.b $FC, $E, $20, $10, $E4
	dc.b $FC, $E, $20, $1C, $4
	dc.b $14, $C, $20, $28, $EC
	dc.b $14, $0, $20, $2C, $C
	dc.b $E1, $6, $0, $4F, $C
	dc.b $EC, $5, $0, $C, $C
DATAEUYQ23E4E2V_1: dc.b $3
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $9, $0, $4, $F4
	dc.b $EC, $1, $0, $2, $EC
DATAEUYQ23E4E2V_2: dc.b $3
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $9, $0, $4, $F4
	dc.b $EC, $1, $0, $2, $EC
DATAEUYQ23E4E2V_3: dc.b $3
	dc.b $E4, $4, $0, $37, $F4
	dc.b $EC, $9, $0, $39, $F4
	dc.b $EC, $1, $0, $2, $EC
DATAEUYQ23E4E2V_4: dc.b $3
	dc.b $E4, $4, $0, $37, $F4
	dc.b $EC, $9, $0, $39, $F4
	dc.b $EC, $1, $0, $2, $EC
DATAEUYQ23E4E2V_5: dc.b $3
	dc.b $E4, $4, $0, $3F, $F4
	dc.b $EC, $9, $0, $41, $F4
	dc.b $EC, $1, $0, $2, $EC
DATAEUYQ23E4E2V_6: dc.b $3
	dc.b $E4, $4, $0, $0, $F4
	dc.b $E4, $4, $0, $35, $4
	dc.b $EC, $D, $0, $2, $EC
DATAEUYQ23E4E2V_7: dc.b $3
	dc.b $E4, $4, $0, $47, $F4
	dc.b $EC, $9, $0, $49, $F4
	dc.b $EC, $1, $0, $2, $EC
DATAEUYQ23E4E2V_8: dc.b $1
	dc.b $4, $5, $0, $2D, $22
DATAEUYQ23E4E2V_9: dc.b $1
	dc.b $4, $5, $0, $31, $22
DATAEUYQ23E4E2V_A: dc.b $0
DATAEUYQ23E4E2V_B: dc.b $2
	dc.b $0, $8, $0, $EF, $22
	dc.b $8, $8, $10, $EF, $22
DATAEUYQ23E4E2V_C: dc.b $2
	dc.b $F8, $B, $0, $F2, $22
	dc.b $0, $1, $0, $FE, $3A
	even