; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Aug 19 2021 20:27:33 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAVFSEUSDQKF:
	dc.w DATAVFSEUSDQKF_0-DATAVFSEUSDQKF, DATAVFSEUSDQKF_1-DATAVFSEUSDQKF
	dc.w DATAVFSEUSDQKF_2-DATAVFSEUSDQKF, DATAVFSEUSDQKF_3-DATAVFSEUSDQKF
	dc.w DATAVFSEUSDQKF_4-DATAVFSEUSDQKF
DATAVFSEUSDQKF_0: dc.b $3
	dc.b $F9, $F, $0, $1D, $EC
	dc.b $19, $0, $0, $2D, $FC
	dc.b $F9, $3, $0, $2E, $C
DATAVFSEUSDQKF_1: dc.b $2
	dc.b $F9, $B, $0, $32, $F4
	dc.b $19, $0, $0, $3E, $FC
DATAVFSEUSDQKF_2: dc.b $2
	dc.b $F9, $3, $0, $18, $FC
	dc.b $19, $0, $0, $1C, $FC
DATAVFSEUSDQKF_3: dc.b $3
	dc.b $F9, $B, $0, $3F, $F4
	dc.b $F1, $4, $0, $4B, $FC
	dc.b $19, $0, $0, $4D, $FC
DATAVFSEUSDQKF_4: dc.b $4
	dc.b $F9, $F, $0, $0, $EC
	dc.b $F1, $8, $0, $10, $F4
	dc.b $19, $0, $0, $13, $FC
	dc.b $F9, $3, $0, $14, $C
	even