; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Aug 19 2021 20:35:24 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA2HHPFLST6DW:
	dc.w DATA2HHPFLST6DW_0-DATA2HHPFLST6DW, DATA2HHPFLST6DW_1-DATA2HHPFLST6DW
	dc.w DATA2HHPFLST6DW_2-DATA2HHPFLST6DW, DATA2HHPFLST6DW_3-DATA2HHPFLST6DW
	dc.w DATA2HHPFLST6DW_4-DATA2HHPFLST6DW
DATA2HHPFLST6DW_0: dc.b $3
	dc.b $F9, $F, $0, $1B, $EC
	dc.b $19, $0, $0, $2B, $FC
	dc.b $F9, $3, $0, $2C, $C
DATA2HHPFLST6DW_1: dc.b $2
	dc.b $F9, $B, $0, $30, $F4
	dc.b $19, $0, $0, $2B, $FC
DATA2HHPFLST6DW_2: dc.b $2
	dc.b $F9, $3, $0, $17, $FC
	dc.b $19, $0, $0, $2B, $FC
DATA2HHPFLST6DW_3: dc.b $5
	dc.b $19, $0, $0, $2B, $FC
	dc.b $F9, $3, $8, $30, $4
	dc.b $F9, $2, $8, $34, $FC
	dc.b $F9, $3, $8, $38, $F4
	dc.b $11, $0, $0, $37, $FC
DATA2HHPFLST6DW_4: dc.b $4
	dc.b $F9, $F, $0, $0, $EC
	dc.b $F1, $8, $0, $10, $F4
	dc.b $F9, $3, $0, $13, $C
	dc.b $19, $0, $0, $2B, $FC
	even