; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Aug 24 2021 16:18:23 GMT+0100 (GMT Summer Time)
; ================================================================================

DATA2X8JESHHCG3:
	dc.w $0, DATA2X8JESHHCG3_1-DATA2X8JESHHCG3
	dc.w DATA2X8JESHHCG3_2-DATA2X8JESHHCG3, DATA2X8JESHHCG3_3-DATA2X8JESHHCG3
DATA2X8JESHHCG3_1: dc.b $6
	dc.b $0, $C, $0, $F2, $0
	dc.b $0, $0, $0, $F5, $20
	dc.b $0, $C, $0, $F5, $30
	dc.b $0, $0, $0, $F6, $50
	dc.b $0, $C, $0, $FA, $5F
	dc.b $0, $4, $0, $FE, $7F
DATA2X8JESHHCG3_2: dc.b $1E
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
DATA2X8JESHHCG3_3: dc.b $1
	dc.b $FC, $4, $0, $0, $F8
	even