; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Aug 17 2021 17:33:23 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAUS91GQGT05:
	dc.w DATAUS91GQGT05_0-DATAUS91GQGT05, DATAUS91GQGT05_1-DATAUS91GQGT05
	dc.w DATAUS91GQGT05_2-DATAUS91GQGT05, DATAUS91GQGT05_3-DATAUS91GQGT05
	dc.w DATAUS91GQGT05_4-DATAUS91GQGT05, DATAUS91GQGT05_5-DATAUS91GQGT05
	dc.w DATAUS91GQGT05_6-DATAUS91GQGT05, DATAUS91GQGT05_7-DATAUS91GQGT05
DATAUS91GQGT05_0: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $FC
DATAUS91GQGT05_1: dc.b $2
	dc.b $EC, $A, $0, $D, $F4
	dc.b $4, $5, $0, $16, $FC
DATAUS91GQGT05_2: dc.b $2
	dc.b $EC, $A, $0, $1A, $F4
	dc.b $4, $5, $0, $23, $FC
DATAUS91GQGT05_3: dc.b $2
	dc.b $EA, $F, $8, $27, $F0
	dc.b $A, $5, $8, $37, $F8
DATAUS91GQGT05_4: dc.b $2
	dc.b $EA, $F, $0, $27, $F0
	dc.b $A, $5, $0, $37, $F8
DATAUS91GQGT05_5: dc.b $2
	dc.b $F4, $F, $0, $3B, $F0
	dc.b $EC, $4, $0, $4B, $F8
DATAUS91GQGT05_6: dc.b $5
	dc.b $B1, $F, $0, $4D, $F4
	dc.b $B9, $3, $0, $5D, $EC
	dc.b $D1, $F, $0, $61, $F4
	dc.b $E1, $2, $0, $71, $EC
	dc.b $F1, $4, $0, $74, $F4
DATAUS91GQGT05_7: dc.b $1B
	dc.b $7E, $F, $0, $76, $E7
	dc.b $7E, $F, $0, $86, $7
	dc.b $7E, $7, $0, $96, $3F
	dc.b $86, $3, $0, $9E, $DF
	dc.b $86, $7, $0, $A2, $2F
	dc.b $8E, $3, $0, $AA, $D7
	dc.b $8E, $3, $0, $AE, $27
	dc.b $9E, $F, $0, $B2, $E7
	dc.b $9E, $F, $0, $C2, $7
	dc.b $9E, $4, $0, $D2, $3F
	dc.b $A6, $1, $0, $D4, $DF
	dc.b $A6, $B, $0, $D6, $2F
	dc.b $AE, $3, $0, $E2, $27
	dc.b $AE, $7, $0, $E6, $47
	dc.b $BE, $F, $0, $EE, $EF
	dc.b $BE, $9, $0, $FE, $F
	dc.b $C6, $B, $1, $4, $2F
	dc.b $CE, $3, $1, $10, $E7
	dc.b $CE, $5, $1, $14, $1F
	dc.b $CE, $4, $1, $18, $47
	dc.b $DE, $8, $1, $1A, $F7
	dc.b $DE, $0, $1, $1D, $27
	dc.b $E6, $5, $1, $1E, $FF
	dc.b $EE, $9, $1, $22, $E7
	dc.b $F6, $1, $1, $28, $DF
	dc.b $FE, $0, $1, $2A, $E7
	dc.b $FE, $0, $1, $2B, $F7
	even