; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Aug 16 2021 22:46:17 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAKV0P1475P3C:
	dc.w $0, DATAKV0P1475P3C_1-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_2-DATAKV0P1475P3C, DATAKV0P1475P3C_3-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_4-DATAKV0P1475P3C, DATAKV0P1475P3C_5-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_6-DATAKV0P1475P3C, DATAKV0P1475P3C_7-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_8-DATAKV0P1475P3C, DATAKV0P1475P3C_9-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_A-DATAKV0P1475P3C, DATAKV0P1475P3C_B-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_C-DATAKV0P1475P3C, DATAKV0P1475P3C_D-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_E-DATAKV0P1475P3C, DATAKV0P1475P3C_F-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_10-DATAKV0P1475P3C, DATAKV0P1475P3C_11-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_12-DATAKV0P1475P3C, DATAKV0P1475P3C_13-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_14-DATAKV0P1475P3C, DATAKV0P1475P3C_15-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_16-DATAKV0P1475P3C, DATAKV0P1475P3C_17-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_18-DATAKV0P1475P3C, DATAKV0P1475P3C_19-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_1A-DATAKV0P1475P3C, DATAKV0P1475P3C_1B-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_1C-DATAKV0P1475P3C, DATAKV0P1475P3C_1D-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_1E-DATAKV0P1475P3C, DATAKV0P1475P3C_1F-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_20-DATAKV0P1475P3C, DATAKV0P1475P3C_21-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_22-DATAKV0P1475P3C, DATAKV0P1475P3C_23-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_24-DATAKV0P1475P3C, DATAKV0P1475P3C_25-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_26-DATAKV0P1475P3C, DATAKV0P1475P3C_27-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_28-DATAKV0P1475P3C, DATAKV0P1475P3C_29-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_2A-DATAKV0P1475P3C, DATAKV0P1475P3C_2B-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_2C-DATAKV0P1475P3C, DATAKV0P1475P3C_2D-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_2E-DATAKV0P1475P3C, DATAKV0P1475P3C_2F-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_30-DATAKV0P1475P3C, DATAKV0P1475P3C_31-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_32-DATAKV0P1475P3C, DATAKV0P1475P3C_33-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_34-DATAKV0P1475P3C, DATAKV0P1475P3C_35-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_36-DATAKV0P1475P3C, DATAKV0P1475P3C_37-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_38-DATAKV0P1475P3C, DATAKV0P1475P3C_39-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_3A-DATAKV0P1475P3C, DATAKV0P1475P3C_3B-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_3C-DATAKV0P1475P3C, DATAKV0P1475P3C_3D-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_3E-DATAKV0P1475P3C, DATAKV0P1475P3C_3F-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_40-DATAKV0P1475P3C, DATAKV0P1475P3C_41-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_42-DATAKV0P1475P3C, DATAKV0P1475P3C_43-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_44-DATAKV0P1475P3C, DATAKV0P1475P3C_45-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_46-DATAKV0P1475P3C, DATAKV0P1475P3C_47-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_48-DATAKV0P1475P3C, $0
	dc.w $0, $0
	dc.w DATAKV0P1475P3C_4C-DATAKV0P1475P3C, DATAKV0P1475P3C_4D-DATAKV0P1475P3C
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATAKV0P1475P3C_53-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_54-DATAKV0P1475P3C, DATAKV0P1475P3C_55-DATAKV0P1475P3C
	dc.w DATAKV0P1475P3C_56-DATAKV0P1475P3C, DATAKV0P1475P3C_57-DATAKV0P1475P3C
DATAKV0P1475P3C_1: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAKV0P1475P3C_2: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAKV0P1475P3C_3: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAKV0P1475P3C_4: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAKV0P1475P3C_5: dc.b $3
	dc.b $ED, $D, $0, $0, $ED
	dc.b $FD, $6, $0, $8, $F5
	dc.b $D, $0, $0, $E, $5
DATAKV0P1475P3C_6: dc.b $4
	dc.b $C, $4, $0, $0, $E7
	dc.b $EC, $F, $0, $2, $EF
	dc.b $C, $0, $0, $12, $7
	dc.b $4, $0, $0, $13, $F
DATAKV0P1475P3C_7: dc.b $2
	dc.b $EE, $E, $0, $0, $EF
	dc.b $6, $5, $0, $C, $F7
DATAKV0P1475P3C_8: dc.b $2
	dc.b $ED, $F, $0, $0, $F0
	dc.b $D, $C, $0, $10, $F0
DATAKV0P1475P3C_9: dc.b $3
	dc.b $7, $5, $0, $0, $E7
	dc.b $E7, $E, $0, $4, $EF
	dc.b $FF, $D, $0, $10, $F7
DATAKV0P1475P3C_A: dc.b $2
	dc.b $EE, $E, $0, $0, $EF
	dc.b $6, $5, $0, $C, $F7
DATAKV0P1475P3C_B: dc.b $2
	dc.b $ED, $E, $0, $0, $F0
	dc.b $5, $9, $0, $C, $F0
DATAKV0P1475P3C_C: dc.b $3
	dc.b $E9, $B, $0, $0, $EA
	dc.b $9, $1, $0, $C, $FA
	dc.b $F1, $6, $0, $E, $2
DATAKV0P1475P3C_D: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $C, $0, $C, $F2
	dc.b $E, $4, $0, $10, $2
DATAKV0P1475P3C_E: dc.b $4
	dc.b $ED, $A, $0, $0, $EA
	dc.b $5, $C, $0, $9, $F2
	dc.b $D, $8, $0, $D, $FA
	dc.b $FD, $8, $0, $10, $2
DATAKV0P1475P3C_F: dc.b $4
	dc.b $EA, $A, $0, $0, $EB
	dc.b $2, $8, $0, $9, $F3
	dc.b $A, $1, $0, $C, $FB
	dc.b $F2, $5, $0, $E, $3
DATAKV0P1475P3C_10: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $C, $0, $C, $F2
	dc.b $E, $4, $0, $10, $2
DATAKV0P1475P3C_11: dc.b $4
	dc.b $ED, $E, $0, $0, $E8
	dc.b $5, $C, $0, $C, $F0
	dc.b $D, $8, $0, $10, $F8
	dc.b $FD, $0, $0, $13, $8
DATAKV0P1475P3C_12: dc.b $4
	dc.b $F0, $F, $0, $0, $EC
	dc.b $E8, $0, $0, $10, $4
	dc.b $F0, $0, $0, $11, $C
	dc.b $8, $1, $0, $12, $C
DATAKV0P1475P3C_13: dc.b $2
	dc.b $F0, $B, $0, $0, $ED
	dc.b $F8, $5, $0, $C, $5
DATAKV0P1475P3C_14: dc.b $2
	dc.b $F0, $F, $0, $0, $ED
	dc.b $F0, $3, $0, $10, $D
DATAKV0P1475P3C_15: dc.b $3
	dc.b $E9, $7, $0, $0, $FF
	dc.b $F1, $B, $0, $8, $E7
	dc.b $9, $5, $0, $14, $7
DATAKV0P1475P3C_16: dc.b $2
	dc.b $F1, $B, $0, $0, $ED
	dc.b $F9, $5, $0, $C, $5
DATAKV0P1475P3C_17: dc.b $2
	dc.b $EF, $B, $0, $0, $EC
	dc.b $F7, $6, $0, $C, $4
DATAKV0P1475P3C_18: dc.b $3
	dc.b $FE, $E, $0, $0, $E7
	dc.b $EE, $9, $0, $C, $EF
	dc.b $FE, $4, $0, $12, $7
DATAKV0P1475P3C_19: dc.b $3
	dc.b $EE, $5, $0, $0, $3
	dc.b $F6, $B, $0, $4, $EB
	dc.b $FE, $1, $0, $10, $3
DATAKV0P1475P3C_1A: dc.b $4
	dc.b $FD, $A, $0, $0, $EA
	dc.b $E5, $2, $0, $9, $FA
	dc.b $ED, $6, $0, $C, $2
	dc.b $5, $0, $0, $12, $2
DATAKV0P1475P3C_1B: dc.b $4
	dc.b $FE, $A, $0, $0, $E8
	dc.b $EE, $5, $0, $9, $F0
	dc.b $F6, $2, $0, $D, $0
	dc.b $FE, $4, $0, $10, $8
DATAKV0P1475P3C_1C: dc.b $3
	dc.b $EE, $5, $0, $0, $3
	dc.b $F6, $B, $0, $4, $EB
	dc.b $FE, $1, $0, $10, $3
DATAKV0P1475P3C_1D: dc.b $4
	dc.b $F7, $E, $0, $0, $EA
	dc.b $F, $8, $0, $C, $EA
	dc.b $EF, $8, $0, $F, $FA
	dc.b $F7, $1, $0, $12, $A
DATAKV0P1475P3C_1E: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAKV0P1475P3C_1F: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAKV0P1475P3C_20: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAKV0P1475P3C_21: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAKV0P1475P3C_22: dc.b $3
	dc.b $ED, $E, $0, $0, $EB
	dc.b $5, $9, $0, $C, $F3
	dc.b $FD, $1, $0, $12, $B
DATAKV0P1475P3C_23: dc.b $3
	dc.b $ED, $D, $0, $0, $E9
	dc.b $FD, $A, $0, $8, $F1
	dc.b $F5, $2, $0, $11, $9
DATAKV0P1475P3C_24: dc.b $3
	dc.b $ED, $E, $0, $0, $EB
	dc.b $5, $9, $0, $C, $F3
	dc.b $FD, $1, $0, $12, $B
DATAKV0P1475P3C_25: dc.b $3
	dc.b $ED, $D, $0, $0, $E9
	dc.b $FD, $A, $0, $8, $F1
	dc.b $F5, $2, $0, $11, $9
DATAKV0P1475P3C_26: dc.b $2
	dc.b $EC, $7, $0, $0, $EC
	dc.b $F4, $B, $0, $8, $FC
DATAKV0P1475P3C_27: dc.b $3
	dc.b $F2, $E, $0, $0, $EB
	dc.b $A, $4, $0, $C, $FB
	dc.b $F2, $2, $0, $E, $B
DATAKV0P1475P3C_28: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
DATAKV0P1475P3C_29: dc.b $3
	dc.b $F2, $E, $0, $0, $EB
	dc.b $A, $4, $0, $C, $FB
	dc.b $F2, $2, $0, $E, $B
DATAKV0P1475P3C_2A: dc.b $3
	dc.b $ED, $F, $0, $0, $F2
	dc.b $F5, $2, $0, $10, $EA
	dc.b $D, $0, $0, $13, $F2
DATAKV0P1475P3C_2B: dc.b $3
	dc.b $ED, $F, $0, $0, $F2
	dc.b $F5, $2, $0, $10, $EA
	dc.b $D, $0, $0, $13, $F2
DATAKV0P1475P3C_2C: dc.b $3
	dc.b $EB, $F, $0, $0, $F2
	dc.b $F3, $2, $0, $10, $EA
	dc.b $B, $0, $0, $13, $F2
DATAKV0P1475P3C_2D: dc.b $3
	dc.b $EC, $F, $0, $0, $F2
	dc.b $F4, $2, $0, $10, $EA
	dc.b $C, $0, $0, $13, $F2
DATAKV0P1475P3C_2E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAKV0P1475P3C_2F: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAKV0P1475P3C_30: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAKV0P1475P3C_31: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAKV0P1475P3C_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAKV0P1475P3C_33: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAKV0P1475P3C_34: dc.b $1
	dc.b $F1, $F, $10, $0, $F1
DATAKV0P1475P3C_35: dc.b $1
	dc.b $F1, $F, $18, $0, $F1
DATAKV0P1475P3C_36: dc.b $1
	dc.b $F1, $F, $8, $0, $F1
DATAKV0P1475P3C_37: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $FC, $3, $0, $C, $8
	dc.b $C, $0, $0, $10, $0
DATAKV0P1475P3C_38: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $FC, $3, $0, $C, $8
	dc.b $C, $0, $0, $10, $0
DATAKV0P1475P3C_39: dc.b $1
	dc.b $FE, $A, $0, $0, $F6
DATAKV0P1475P3C_3A: dc.b $2
	dc.b $5, $D, $0, $0, $E1
	dc.b $ED, $E, $0, $8, $E9
DATAKV0P1475P3C_3B: dc.b $2
	dc.b $5, $D, $0, $0, $E2
	dc.b $ED, $E, $0, $8, $EA
DATAKV0P1475P3C_3C: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAKV0P1475P3C_3D: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAKV0P1475P3C_3E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAKV0P1475P3C_3F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAKV0P1475P3C_40: dc.b $2
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
DATAKV0P1475P3C_41: dc.b $2
	dc.b $F8, $E, $0, $0, $E8
	dc.b $F8, $6, $0, $C, $8
DATAKV0P1475P3C_42: dc.b $2
	dc.b $F7, $E, $0, $0, $E8
	dc.b $F7, $6, $0, $C, $8
DATAKV0P1475P3C_43: dc.b $2
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
DATAKV0P1475P3C_44: dc.b $2
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
DATAKV0P1475P3C_45: dc.b $2
	dc.b $9, $D, $0, $0, $EB
	dc.b $F1, $A, $0, $8, $F3
DATAKV0P1475P3C_46: dc.b $2
	dc.b $F0, $A, $0, $0, $F3
	dc.b $8, $5, $0, $9, $F3
DATAKV0P1475P3C_47: dc.b $2
	dc.b $5, $D, $0, $0, $EB
	dc.b $ED, $A, $0, $8, $F3
DATAKV0P1475P3C_48: dc.b $2
	dc.b $F0, $A, $0, $0, $F3
	dc.b $8, $5, $0, $9, $F3
DATAKV0P1475P3C_4C: dc.b $2
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $D, $0, $C, $F0
DATAKV0P1475P3C_4D: dc.b $2
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $D, $0, $C, $F0
DATAKV0P1475P3C_53: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAKV0P1475P3C_54: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAKV0P1475P3C_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $8, $8, $0, $C, $F4
	dc.b $F8, $1, $0, $F, $C
DATAKV0P1475P3C_56: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $C, $0, $C, $F0
	dc.b $F4, $2, $0, $10, $8
DATAKV0P1475P3C_57: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $8, $8, $0, $C, $F4
	dc.b $F8, $1, $0, $F, $C
	even