; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Aug 17 2021 21:41:09 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAW600QRXD9A:
	dc.w $0, DATAW600QRXD9A_1-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_2-DATAW600QRXD9A, DATAW600QRXD9A_3-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_4-DATAW600QRXD9A, DATAW600QRXD9A_5-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_6-DATAW600QRXD9A, DATAW600QRXD9A_7-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_8-DATAW600QRXD9A, DATAW600QRXD9A_9-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_A-DATAW600QRXD9A, DATAW600QRXD9A_B-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_C-DATAW600QRXD9A, DATAW600QRXD9A_D-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_E-DATAW600QRXD9A, DATAW600QRXD9A_F-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_10-DATAW600QRXD9A, DATAW600QRXD9A_11-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_12-DATAW600QRXD9A, DATAW600QRXD9A_13-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_14-DATAW600QRXD9A, DATAW600QRXD9A_15-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_16-DATAW600QRXD9A, DATAW600QRXD9A_17-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_18-DATAW600QRXD9A, DATAW600QRXD9A_19-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_1A-DATAW600QRXD9A, DATAW600QRXD9A_1B-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_1C-DATAW600QRXD9A, DATAW600QRXD9A_1D-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_1E-DATAW600QRXD9A, DATAW600QRXD9A_1F-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_20-DATAW600QRXD9A, DATAW600QRXD9A_21-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_22-DATAW600QRXD9A, DATAW600QRXD9A_23-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_24-DATAW600QRXD9A, DATAW600QRXD9A_25-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_26-DATAW600QRXD9A, DATAW600QRXD9A_27-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_28-DATAW600QRXD9A, DATAW600QRXD9A_29-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_2A-DATAW600QRXD9A, DATAW600QRXD9A_2B-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_2C-DATAW600QRXD9A, DATAW600QRXD9A_2D-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_2E-DATAW600QRXD9A, DATAW600QRXD9A_2F-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_30-DATAW600QRXD9A, DATAW600QRXD9A_31-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_32-DATAW600QRXD9A, DATAW600QRXD9A_33-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_34-DATAW600QRXD9A, DATAW600QRXD9A_35-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_36-DATAW600QRXD9A, DATAW600QRXD9A_37-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_38-DATAW600QRXD9A, DATAW600QRXD9A_39-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_3A-DATAW600QRXD9A, DATAW600QRXD9A_3B-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_3C-DATAW600QRXD9A, DATAW600QRXD9A_3D-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_3E-DATAW600QRXD9A, DATAW600QRXD9A_3F-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_40-DATAW600QRXD9A, DATAW600QRXD9A_41-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_42-DATAW600QRXD9A, DATAW600QRXD9A_43-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_44-DATAW600QRXD9A, DATAW600QRXD9A_45-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_46-DATAW600QRXD9A, DATAW600QRXD9A_47-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_48-DATAW600QRXD9A, $0
	dc.w $0, $0
	dc.w DATAW600QRXD9A_4C-DATAW600QRXD9A, DATAW600QRXD9A_4D-DATAW600QRXD9A
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATAW600QRXD9A_53-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_54-DATAW600QRXD9A, DATAW600QRXD9A_55-DATAW600QRXD9A
	dc.w DATAW600QRXD9A_56-DATAW600QRXD9A, DATAW600QRXD9A_57-DATAW600QRXD9A
DATAW600QRXD9A_1: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAW600QRXD9A_2: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAW600QRXD9A_3: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAW600QRXD9A_4: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAW600QRXD9A_5: dc.b $3
	dc.b $ED, $D, $0, $0, $ED
	dc.b $FD, $6, $0, $8, $F5
	dc.b $D, $0, $0, $E, $5
DATAW600QRXD9A_6: dc.b $4
	dc.b $C, $4, $0, $0, $E7
	dc.b $EC, $F, $0, $2, $EF
	dc.b $C, $0, $0, $12, $7
	dc.b $4, $0, $0, $13, $F
DATAW600QRXD9A_7: dc.b $2
	dc.b $EE, $E, $0, $0, $EF
	dc.b $6, $5, $0, $C, $F7
DATAW600QRXD9A_8: dc.b $2
	dc.b $ED, $F, $0, $0, $F0
	dc.b $D, $C, $0, $10, $F0
DATAW600QRXD9A_9: dc.b $3
	dc.b $7, $5, $0, $0, $E7
	dc.b $E7, $E, $0, $4, $EF
	dc.b $FF, $D, $0, $10, $F7
DATAW600QRXD9A_A: dc.b $2
	dc.b $EE, $E, $0, $0, $EF
	dc.b $6, $5, $0, $C, $F7
DATAW600QRXD9A_B: dc.b $2
	dc.b $ED, $E, $0, $0, $F0
	dc.b $5, $9, $0, $C, $F0
DATAW600QRXD9A_C: dc.b $3
	dc.b $E9, $B, $0, $0, $EA
	dc.b $9, $1, $0, $C, $FA
	dc.b $F1, $6, $0, $E, $2
DATAW600QRXD9A_D: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $C, $0, $C, $F2
	dc.b $E, $4, $0, $10, $2
DATAW600QRXD9A_E: dc.b $4
	dc.b $ED, $A, $0, $0, $EA
	dc.b $5, $C, $0, $9, $F2
	dc.b $D, $8, $0, $D, $FA
	dc.b $FD, $8, $0, $10, $2
DATAW600QRXD9A_F: dc.b $4
	dc.b $EA, $A, $0, $0, $EB
	dc.b $2, $8, $0, $9, $F3
	dc.b $A, $1, $0, $C, $FB
	dc.b $F2, $5, $0, $E, $3
DATAW600QRXD9A_10: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $C, $0, $C, $F2
	dc.b $E, $4, $0, $10, $2
DATAW600QRXD9A_11: dc.b $4
	dc.b $ED, $E, $0, $0, $E8
	dc.b $5, $C, $0, $C, $F0
	dc.b $D, $8, $0, $10, $F8
	dc.b $FD, $0, $0, $13, $8
DATAW600QRXD9A_12: dc.b $4
	dc.b $F0, $F, $0, $0, $EC
	dc.b $E8, $0, $0, $10, $4
	dc.b $F0, $0, $0, $11, $C
	dc.b $8, $1, $0, $12, $C
DATAW600QRXD9A_13: dc.b $2
	dc.b $F0, $B, $0, $0, $ED
	dc.b $F8, $5, $0, $C, $5
DATAW600QRXD9A_14: dc.b $2
	dc.b $F0, $F, $0, $0, $ED
	dc.b $F0, $3, $0, $10, $D
DATAW600QRXD9A_15: dc.b $3
	dc.b $E9, $7, $0, $0, $FF
	dc.b $F1, $B, $0, $8, $E7
	dc.b $9, $5, $0, $14, $7
DATAW600QRXD9A_16: dc.b $2
	dc.b $F1, $B, $0, $0, $ED
	dc.b $F9, $5, $0, $C, $5
DATAW600QRXD9A_17: dc.b $2
	dc.b $EF, $B, $0, $0, $EC
	dc.b $F7, $6, $0, $C, $4
DATAW600QRXD9A_18: dc.b $3
	dc.b $FE, $E, $0, $0, $E7
	dc.b $EE, $9, $0, $C, $EF
	dc.b $FE, $4, $0, $12, $7
DATAW600QRXD9A_19: dc.b $3
	dc.b $EE, $5, $0, $0, $3
	dc.b $F6, $B, $0, $4, $EB
	dc.b $FE, $1, $0, $10, $3
DATAW600QRXD9A_1A: dc.b $4
	dc.b $FD, $A, $0, $0, $EA
	dc.b $E5, $2, $0, $9, $FA
	dc.b $ED, $6, $0, $C, $2
	dc.b $5, $0, $0, $12, $2
DATAW600QRXD9A_1B: dc.b $4
	dc.b $FE, $A, $0, $0, $E8
	dc.b $EE, $5, $0, $9, $F0
	dc.b $F6, $2, $0, $D, $0
	dc.b $FE, $4, $0, $10, $8
DATAW600QRXD9A_1C: dc.b $3
	dc.b $EE, $5, $0, $0, $3
	dc.b $F6, $B, $0, $4, $EB
	dc.b $FE, $1, $0, $10, $3
DATAW600QRXD9A_1D: dc.b $4
	dc.b $F7, $E, $0, $0, $EA
	dc.b $F, $8, $0, $C, $EA
	dc.b $EF, $8, $0, $F, $FA
	dc.b $F7, $1, $0, $12, $A
DATAW600QRXD9A_1E: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAW600QRXD9A_1F: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAW600QRXD9A_20: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAW600QRXD9A_21: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAW600QRXD9A_22: dc.b $3
	dc.b $ED, $E, $0, $0, $EB
	dc.b $5, $9, $0, $C, $F3
	dc.b $FD, $1, $0, $12, $B
DATAW600QRXD9A_23: dc.b $3
	dc.b $ED, $D, $0, $0, $E9
	dc.b $FD, $A, $0, $8, $F1
	dc.b $F5, $2, $0, $11, $9
DATAW600QRXD9A_24: dc.b $3
	dc.b $ED, $E, $0, $0, $EB
	dc.b $5, $9, $0, $C, $F3
	dc.b $FD, $1, $0, $12, $B
DATAW600QRXD9A_25: dc.b $3
	dc.b $ED, $D, $0, $0, $E9
	dc.b $FD, $A, $0, $8, $F1
	dc.b $F5, $2, $0, $11, $9
DATAW600QRXD9A_26: dc.b $2
	dc.b $EC, $7, $0, $0, $EC
	dc.b $F4, $B, $0, $8, $FC
DATAW600QRXD9A_27: dc.b $3
	dc.b $F2, $E, $0, $0, $EB
	dc.b $A, $4, $0, $C, $FB
	dc.b $F2, $2, $0, $E, $B
DATAW600QRXD9A_28: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
DATAW600QRXD9A_29: dc.b $3
	dc.b $F2, $E, $0, $0, $EB
	dc.b $A, $4, $0, $C, $FB
	dc.b $F2, $2, $0, $E, $B
DATAW600QRXD9A_2A: dc.b $3
	dc.b $ED, $F, $0, $0, $F2
	dc.b $F5, $2, $0, $10, $EA
	dc.b $D, $0, $0, $13, $F2
DATAW600QRXD9A_2B: dc.b $3
	dc.b $ED, $F, $0, $0, $F2
	dc.b $F5, $2, $0, $10, $EA
	dc.b $D, $0, $0, $13, $F2
DATAW600QRXD9A_2C: dc.b $3
	dc.b $EB, $F, $0, $0, $F2
	dc.b $F3, $2, $0, $10, $EA
	dc.b $B, $0, $0, $13, $F2
DATAW600QRXD9A_2D: dc.b $3
	dc.b $EC, $F, $0, $0, $F2
	dc.b $F4, $2, $0, $10, $EA
	dc.b $C, $0, $0, $13, $F2
DATAW600QRXD9A_2E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAW600QRXD9A_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F2
DATAW600QRXD9A_30: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAW600QRXD9A_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F2
DATAW600QRXD9A_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAW600QRXD9A_33: dc.b $1
	dc.b $F4, $F, $0, $0, $F1
DATAW600QRXD9A_34: dc.b $1
	dc.b $F4, $F, $10, $0, $F1
DATAW600QRXD9A_35: dc.b $1
	dc.b $F4, $F, $18, $0, $F1
DATAW600QRXD9A_36: dc.b $1
	dc.b $F4, $F, $8, $0, $F1
DATAW600QRXD9A_37: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $FC, $3, $0, $C, $8
	dc.b $C, $0, $0, $10, $0
DATAW600QRXD9A_38: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $FC, $3, $0, $C, $8
	dc.b $C, $0, $0, $10, $0
DATAW600QRXD9A_39: dc.b $1
	dc.b $FE, $A, $0, $0, $F6
DATAW600QRXD9A_3A: dc.b $2
	dc.b $5, $D, $0, $0, $E1
	dc.b $ED, $E, $0, $8, $E9
DATAW600QRXD9A_3B: dc.b $2
	dc.b $5, $D, $0, $0, $E2
	dc.b $ED, $E, $0, $8, $EA
DATAW600QRXD9A_3C: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAW600QRXD9A_3D: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAW600QRXD9A_3E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAW600QRXD9A_3F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAW600QRXD9A_40: dc.b $2
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
DATAW600QRXD9A_41: dc.b $2
	dc.b $F8, $E, $0, $0, $E8
	dc.b $F8, $6, $0, $C, $8
DATAW600QRXD9A_42: dc.b $2
	dc.b $F7, $E, $0, $0, $E8
	dc.b $F7, $6, $0, $C, $8
DATAW600QRXD9A_43: dc.b $2
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
DATAW600QRXD9A_44: dc.b $2
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
DATAW600QRXD9A_45: dc.b $2
	dc.b $9, $D, $0, $0, $EB
	dc.b $F1, $A, $0, $8, $F3
DATAW600QRXD9A_46: dc.b $2
	dc.b $F0, $A, $0, $0, $F3
	dc.b $8, $5, $0, $9, $F3
DATAW600QRXD9A_47: dc.b $2
	dc.b $5, $D, $0, $0, $EB
	dc.b $ED, $A, $0, $8, $F3
DATAW600QRXD9A_48: dc.b $2
	dc.b $F0, $A, $0, $0, $F3
	dc.b $8, $5, $0, $9, $F3
DATAW600QRXD9A_4C: dc.b $2
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $D, $0, $C, $F0
DATAW600QRXD9A_4D: dc.b $2
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $D, $0, $C, $F0
DATAW600QRXD9A_53: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAW600QRXD9A_54: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAW600QRXD9A_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $8, $8, $0, $C, $F4
	dc.b $F8, $1, $0, $F, $C
DATAW600QRXD9A_56: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $C, $0, $C, $F0
	dc.b $F4, $2, $0, $10, $8
DATAW600QRXD9A_57: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $8, $8, $0, $C, $F4
	dc.b $F8, $1, $0, $F, $C
	even