; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Aug 16 2021 23:04:07 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAOXC6TY763B:
	dc.w $0, DATAOXC6TY763B_1-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_2-DATAOXC6TY763B, DATAOXC6TY763B_3-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_4-DATAOXC6TY763B, DATAOXC6TY763B_5-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_6-DATAOXC6TY763B, DATAOXC6TY763B_7-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_8-DATAOXC6TY763B, DATAOXC6TY763B_9-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_A-DATAOXC6TY763B, DATAOXC6TY763B_B-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_C-DATAOXC6TY763B, DATAOXC6TY763B_D-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_E-DATAOXC6TY763B, DATAOXC6TY763B_F-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_10-DATAOXC6TY763B, DATAOXC6TY763B_11-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_12-DATAOXC6TY763B, DATAOXC6TY763B_13-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_14-DATAOXC6TY763B, DATAOXC6TY763B_15-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_16-DATAOXC6TY763B, DATAOXC6TY763B_17-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_18-DATAOXC6TY763B, DATAOXC6TY763B_19-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_1A-DATAOXC6TY763B, DATAOXC6TY763B_1B-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_1C-DATAOXC6TY763B, DATAOXC6TY763B_1D-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_1E-DATAOXC6TY763B, DATAOXC6TY763B_1F-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_20-DATAOXC6TY763B, DATAOXC6TY763B_21-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_22-DATAOXC6TY763B, DATAOXC6TY763B_23-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_24-DATAOXC6TY763B, DATAOXC6TY763B_25-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_26-DATAOXC6TY763B, DATAOXC6TY763B_27-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_28-DATAOXC6TY763B, DATAOXC6TY763B_29-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_2A-DATAOXC6TY763B, DATAOXC6TY763B_2B-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_2C-DATAOXC6TY763B, DATAOXC6TY763B_2D-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_2E-DATAOXC6TY763B, DATAOXC6TY763B_2F-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_30-DATAOXC6TY763B, DATAOXC6TY763B_31-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_32-DATAOXC6TY763B, DATAOXC6TY763B_33-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_34-DATAOXC6TY763B, DATAOXC6TY763B_35-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_36-DATAOXC6TY763B, DATAOXC6TY763B_37-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_38-DATAOXC6TY763B, DATAOXC6TY763B_39-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_3A-DATAOXC6TY763B, DATAOXC6TY763B_3B-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_3C-DATAOXC6TY763B, DATAOXC6TY763B_3D-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_3E-DATAOXC6TY763B, DATAOXC6TY763B_3F-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_40-DATAOXC6TY763B, DATAOXC6TY763B_41-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_42-DATAOXC6TY763B, DATAOXC6TY763B_43-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_44-DATAOXC6TY763B, DATAOXC6TY763B_45-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_46-DATAOXC6TY763B, DATAOXC6TY763B_47-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_48-DATAOXC6TY763B, $0
	dc.w $0, $0
	dc.w DATAOXC6TY763B_4C-DATAOXC6TY763B, DATAOXC6TY763B_4D-DATAOXC6TY763B
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATAOXC6TY763B_53-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_54-DATAOXC6TY763B, DATAOXC6TY763B_55-DATAOXC6TY763B
	dc.w DATAOXC6TY763B_56-DATAOXC6TY763B, DATAOXC6TY763B_57-DATAOXC6TY763B
DATAOXC6TY763B_1: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAOXC6TY763B_2: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAOXC6TY763B_3: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAOXC6TY763B_4: dc.b $2
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $C, $0, $C, $F0
DATAOXC6TY763B_5: dc.b $3
	dc.b $ED, $D, $0, $0, $ED
	dc.b $FD, $6, $0, $8, $F5
	dc.b $D, $0, $0, $E, $5
DATAOXC6TY763B_6: dc.b $4
	dc.b $C, $4, $0, $0, $E7
	dc.b $EC, $F, $0, $2, $EF
	dc.b $C, $0, $0, $12, $7
	dc.b $4, $0, $0, $13, $F
DATAOXC6TY763B_7: dc.b $2
	dc.b $EE, $E, $0, $0, $EF
	dc.b $6, $5, $0, $C, $F7
DATAOXC6TY763B_8: dc.b $2
	dc.b $ED, $F, $0, $0, $F0
	dc.b $D, $C, $0, $10, $F0
DATAOXC6TY763B_9: dc.b $3
	dc.b $7, $5, $0, $0, $E7
	dc.b $E7, $E, $0, $4, $EF
	dc.b $FF, $D, $0, $10, $F7
DATAOXC6TY763B_A: dc.b $2
	dc.b $EE, $E, $0, $0, $EF
	dc.b $6, $5, $0, $C, $F7
DATAOXC6TY763B_B: dc.b $2
	dc.b $ED, $E, $0, $0, $F0
	dc.b $5, $9, $0, $C, $F0
DATAOXC6TY763B_C: dc.b $3
	dc.b $E9, $B, $0, $0, $EA
	dc.b $9, $1, $0, $C, $FA
	dc.b $F1, $6, $0, $E, $2
DATAOXC6TY763B_D: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $C, $0, $C, $F2
	dc.b $E, $4, $0, $10, $2
DATAOXC6TY763B_E: dc.b $4
	dc.b $ED, $A, $0, $0, $EA
	dc.b $5, $C, $0, $9, $F2
	dc.b $D, $8, $0, $D, $FA
	dc.b $FD, $8, $0, $10, $2
DATAOXC6TY763B_F: dc.b $4
	dc.b $EA, $A, $0, $0, $EB
	dc.b $2, $8, $0, $9, $F3
	dc.b $A, $1, $0, $C, $FB
	dc.b $F2, $5, $0, $E, $3
DATAOXC6TY763B_10: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $C, $0, $C, $F2
	dc.b $E, $4, $0, $10, $2
DATAOXC6TY763B_11: dc.b $4
	dc.b $ED, $E, $0, $0, $E8
	dc.b $5, $C, $0, $C, $F0
	dc.b $D, $8, $0, $10, $F8
	dc.b $FD, $0, $0, $13, $8
DATAOXC6TY763B_12: dc.b $4
	dc.b $F0, $F, $0, $0, $EC
	dc.b $E8, $0, $0, $10, $4
	dc.b $F0, $0, $0, $11, $C
	dc.b $8, $1, $0, $12, $C
DATAOXC6TY763B_13: dc.b $2
	dc.b $F0, $B, $0, $0, $ED
	dc.b $F8, $5, $0, $C, $5
DATAOXC6TY763B_14: dc.b $2
	dc.b $F0, $F, $0, $0, $ED
	dc.b $F0, $3, $0, $10, $D
DATAOXC6TY763B_15: dc.b $3
	dc.b $E9, $7, $0, $0, $FF
	dc.b $F1, $B, $0, $8, $E7
	dc.b $9, $5, $0, $14, $7
DATAOXC6TY763B_16: dc.b $2
	dc.b $F1, $B, $0, $0, $ED
	dc.b $F9, $5, $0, $C, $5
DATAOXC6TY763B_17: dc.b $2
	dc.b $EF, $B, $0, $0, $EC
	dc.b $F7, $6, $0, $C, $4
DATAOXC6TY763B_18: dc.b $3
	dc.b $FE, $E, $0, $0, $E7
	dc.b $EE, $9, $0, $C, $EF
	dc.b $FE, $4, $0, $12, $7
DATAOXC6TY763B_19: dc.b $3
	dc.b $EE, $5, $0, $0, $3
	dc.b $F6, $B, $0, $4, $EB
	dc.b $FE, $1, $0, $10, $3
DATAOXC6TY763B_1A: dc.b $4
	dc.b $FD, $A, $0, $0, $EA
	dc.b $E5, $2, $0, $9, $FA
	dc.b $ED, $6, $0, $C, $2
	dc.b $5, $0, $0, $12, $2
DATAOXC6TY763B_1B: dc.b $4
	dc.b $FE, $A, $0, $0, $E8
	dc.b $EE, $5, $0, $9, $F0
	dc.b $F6, $2, $0, $D, $0
	dc.b $FE, $4, $0, $10, $8
DATAOXC6TY763B_1C: dc.b $3
	dc.b $EE, $5, $0, $0, $3
	dc.b $F6, $B, $0, $4, $EB
	dc.b $FE, $1, $0, $10, $3
DATAOXC6TY763B_1D: dc.b $4
	dc.b $F7, $E, $0, $0, $EA
	dc.b $F, $8, $0, $C, $EA
	dc.b $EF, $8, $0, $F, $FA
	dc.b $F7, $1, $0, $12, $A
DATAOXC6TY763B_1E: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAOXC6TY763B_1F: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAOXC6TY763B_20: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAOXC6TY763B_21: dc.b $2
	dc.b $FD, $E, $0, $0, $F0
	dc.b $ED, $9, $0, $C, $F8
DATAOXC6TY763B_22: dc.b $3
	dc.b $ED, $E, $0, $0, $EB
	dc.b $5, $9, $0, $C, $F3
	dc.b $FD, $1, $0, $12, $B
DATAOXC6TY763B_23: dc.b $3
	dc.b $ED, $D, $0, $0, $E9
	dc.b $FD, $A, $0, $8, $F1
	dc.b $F5, $2, $0, $11, $9
DATAOXC6TY763B_24: dc.b $3
	dc.b $ED, $E, $0, $0, $EB
	dc.b $5, $9, $0, $C, $F3
	dc.b $FD, $1, $0, $12, $B
DATAOXC6TY763B_25: dc.b $3
	dc.b $ED, $D, $0, $0, $E9
	dc.b $FD, $A, $0, $8, $F1
	dc.b $F5, $2, $0, $11, $9
DATAOXC6TY763B_26: dc.b $2
	dc.b $EC, $7, $0, $0, $EC
	dc.b $F4, $B, $0, $8, $FC
DATAOXC6TY763B_27: dc.b $3
	dc.b $F2, $E, $0, $0, $EB
	dc.b $A, $4, $0, $C, $FB
	dc.b $F2, $2, $0, $E, $B
DATAOXC6TY763B_28: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
DATAOXC6TY763B_29: dc.b $3
	dc.b $F2, $E, $0, $0, $EB
	dc.b $A, $4, $0, $C, $FB
	dc.b $F2, $2, $0, $E, $B
DATAOXC6TY763B_2A: dc.b $3
	dc.b $ED, $F, $0, $0, $F2
	dc.b $F5, $2, $0, $10, $EA
	dc.b $D, $0, $0, $13, $F2
DATAOXC6TY763B_2B: dc.b $3
	dc.b $ED, $F, $0, $0, $F2
	dc.b $F5, $2, $0, $10, $EA
	dc.b $D, $0, $0, $13, $F2
DATAOXC6TY763B_2C: dc.b $3
	dc.b $EB, $F, $0, $0, $F2
	dc.b $F3, $2, $0, $10, $EA
	dc.b $B, $0, $0, $13, $F2
DATAOXC6TY763B_2D: dc.b $3
	dc.b $EC, $F, $0, $0, $F2
	dc.b $F4, $2, $0, $10, $EA
	dc.b $C, $0, $0, $13, $F2
DATAOXC6TY763B_2E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAOXC6TY763B_2F: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAOXC6TY763B_30: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAOXC6TY763B_31: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAOXC6TY763B_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAOXC6TY763B_33: dc.b $1
	dc.b $F4, $F, $0, $0, $F1
DATAOXC6TY763B_34: dc.b $1
	dc.b $F4, $F, $10, $0, $F1
DATAOXC6TY763B_35: dc.b $1
	dc.b $F4, $F, $18, $0, $F1
DATAOXC6TY763B_36: dc.b $1
	dc.b $F4, $F, $8, $0, $F1
DATAOXC6TY763B_37: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $FC, $3, $0, $C, $8
	dc.b $C, $0, $0, $10, $0
DATAOXC6TY763B_38: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $FC, $3, $0, $C, $8
	dc.b $C, $0, $0, $10, $0
DATAOXC6TY763B_39: dc.b $1
	dc.b $FE, $A, $0, $0, $F6
DATAOXC6TY763B_3A: dc.b $2
	dc.b $5, $D, $0, $0, $E1
	dc.b $ED, $E, $0, $8, $E9
DATAOXC6TY763B_3B: dc.b $2
	dc.b $5, $D, $0, $0, $E2
	dc.b $ED, $E, $0, $8, $EA
DATAOXC6TY763B_3C: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAOXC6TY763B_3D: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAOXC6TY763B_3E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAOXC6TY763B_3F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAOXC6TY763B_40: dc.b $2
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
DATAOXC6TY763B_41: dc.b $2
	dc.b $F8, $E, $0, $0, $E8
	dc.b $F8, $6, $0, $C, $8
DATAOXC6TY763B_42: dc.b $2
	dc.b $F7, $E, $0, $0, $E8
	dc.b $F7, $6, $0, $C, $8
DATAOXC6TY763B_43: dc.b $2
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
DATAOXC6TY763B_44: dc.b $2
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
DATAOXC6TY763B_45: dc.b $2
	dc.b $9, $D, $0, $0, $EB
	dc.b $F1, $A, $0, $8, $F3
DATAOXC6TY763B_46: dc.b $2
	dc.b $F0, $A, $0, $0, $F3
	dc.b $8, $5, $0, $9, $F3
DATAOXC6TY763B_47: dc.b $2
	dc.b $5, $D, $0, $0, $EB
	dc.b $ED, $A, $0, $8, $F3
DATAOXC6TY763B_48: dc.b $2
	dc.b $F0, $A, $0, $0, $F3
	dc.b $8, $5, $0, $9, $F3
DATAOXC6TY763B_4C: dc.b $2
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $D, $0, $C, $F0
DATAOXC6TY763B_4D: dc.b $2
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $D, $0, $C, $F0
DATAOXC6TY763B_53: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAOXC6TY763B_54: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAOXC6TY763B_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $8, $8, $0, $C, $F4
	dc.b $F8, $1, $0, $F, $C
DATAOXC6TY763B_56: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $C, $0, $C, $F0
	dc.b $F4, $2, $0, $10, $8
DATAOXC6TY763B_57: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $8, $8, $0, $C, $F4
	dc.b $F8, $1, $0, $F, $C
	even