; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Aug 17 2021 16:08:08 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATARVT62CO55QQ:
	dc.w $0, DATARVT62CO55QQ_1-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_2-DATARVT62CO55QQ, DATARVT62CO55QQ_3-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_4-DATARVT62CO55QQ, DATARVT62CO55QQ_5-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_6-DATARVT62CO55QQ, DATARVT62CO55QQ_7-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_8-DATARVT62CO55QQ, DATARVT62CO55QQ_9-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_A-DATARVT62CO55QQ, DATARVT62CO55QQ_B-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_C-DATARVT62CO55QQ, DATARVT62CO55QQ_D-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_E-DATARVT62CO55QQ, DATARVT62CO55QQ_F-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_10-DATARVT62CO55QQ, DATARVT62CO55QQ_11-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_12-DATARVT62CO55QQ, DATARVT62CO55QQ_13-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_14-DATARVT62CO55QQ, DATARVT62CO55QQ_15-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_16-DATARVT62CO55QQ, DATARVT62CO55QQ_17-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_18-DATARVT62CO55QQ, DATARVT62CO55QQ_19-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_1A-DATARVT62CO55QQ, DATARVT62CO55QQ_1B-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_1C-DATARVT62CO55QQ, DATARVT62CO55QQ_1D-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_1E-DATARVT62CO55QQ, DATARVT62CO55QQ_1F-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_20-DATARVT62CO55QQ, DATARVT62CO55QQ_21-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_22-DATARVT62CO55QQ, DATARVT62CO55QQ_23-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_24-DATARVT62CO55QQ, DATARVT62CO55QQ_25-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_26-DATARVT62CO55QQ, DATARVT62CO55QQ_27-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_28-DATARVT62CO55QQ, DATARVT62CO55QQ_29-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_2A-DATARVT62CO55QQ, DATARVT62CO55QQ_2B-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_2C-DATARVT62CO55QQ, DATARVT62CO55QQ_2D-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_2E-DATARVT62CO55QQ, DATARVT62CO55QQ_2F-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_30-DATARVT62CO55QQ, DATARVT62CO55QQ_31-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_32-DATARVT62CO55QQ, DATARVT62CO55QQ_33-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_34-DATARVT62CO55QQ, DATARVT62CO55QQ_35-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_36-DATARVT62CO55QQ, DATARVT62CO55QQ_37-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_38-DATARVT62CO55QQ, DATARVT62CO55QQ_39-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_3A-DATARVT62CO55QQ, DATARVT62CO55QQ_3B-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_3C-DATARVT62CO55QQ, DATARVT62CO55QQ_3D-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_3E-DATARVT62CO55QQ, DATARVT62CO55QQ_3F-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_40-DATARVT62CO55QQ, DATARVT62CO55QQ_41-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_42-DATARVT62CO55QQ, DATARVT62CO55QQ_43-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_44-DATARVT62CO55QQ, DATARVT62CO55QQ_45-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_46-DATARVT62CO55QQ, DATARVT62CO55QQ_47-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_48-DATARVT62CO55QQ, DATARVT62CO55QQ_49-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_4A-DATARVT62CO55QQ, DATARVT62CO55QQ_4B-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_4C-DATARVT62CO55QQ, DATARVT62CO55QQ_4D-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_4E-DATARVT62CO55QQ, DATARVT62CO55QQ_4F-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_50-DATARVT62CO55QQ, DATARVT62CO55QQ_51-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_52-DATARVT62CO55QQ, DATARVT62CO55QQ_53-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_54-DATARVT62CO55QQ, DATARVT62CO55QQ_55-DATARVT62CO55QQ
	dc.w DATARVT62CO55QQ_56-DATARVT62CO55QQ, DATARVT62CO55QQ_57-DATARVT62CO55QQ
DATARVT62CO55QQ_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
DATARVT62CO55QQ_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATARVT62CO55QQ_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATARVT62CO55QQ_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATARVT62CO55QQ_5: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F0
	dc.b $C, $8, $0, $C, $F8
DATARVT62CO55QQ_6: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATARVT62CO55QQ_7: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATARVT62CO55QQ_8: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $A, $0, $6, $F3
DATARVT62CO55QQ_9: dc.b $4
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $9, $0, $6, $EC
	dc.b $FB, $6, $0, $C, $4
	dc.b $B, $4, $0, $12, $EC
DATARVT62CO55QQ_A: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
DATARVT62CO55QQ_B: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATARVT62CO55QQ_C: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
DATARVT62CO55QQ_D: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATARVT62CO55QQ_E: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATARVT62CO55QQ_F: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATARVT62CO55QQ_10: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATARVT62CO55QQ_11: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATARVT62CO55QQ_12: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATARVT62CO55QQ_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATARVT62CO55QQ_14: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATARVT62CO55QQ_15: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
DATARVT62CO55QQ_16: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATARVT62CO55QQ_17: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $EC, $0, $0, $8, $FD
	dc.b $F4, $A, $0, $9, $FD
DATARVT62CO55QQ_18: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATARVT62CO55QQ_19: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATARVT62CO55QQ_1A: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATARVT62CO55QQ_1B: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATARVT62CO55QQ_1C: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATARVT62CO55QQ_1D: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATARVT62CO55QQ_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATARVT62CO55QQ_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATARVT62CO55QQ_20: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATARVT62CO55QQ_21: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATARVT62CO55QQ_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATARVT62CO55QQ_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATARVT62CO55QQ_24: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATARVT62CO55QQ_25: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATARVT62CO55QQ_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATARVT62CO55QQ_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATARVT62CO55QQ_28: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATARVT62CO55QQ_29: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATARVT62CO55QQ_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATARVT62CO55QQ_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATARVT62CO55QQ_2C: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATARVT62CO55QQ_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATARVT62CO55QQ_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATARVT62CO55QQ_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATARVT62CO55QQ_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATARVT62CO55QQ_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATARVT62CO55QQ_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATARVT62CO55QQ_33: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
DATARVT62CO55QQ_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATARVT62CO55QQ_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATARVT62CO55QQ_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATARVT62CO55QQ_37: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
DATARVT62CO55QQ_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
DATARVT62CO55QQ_39: dc.b $4
	dc.b $F4, $4, $0, $0, $FC
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
DATARVT62CO55QQ_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
DATARVT62CO55QQ_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
DATARVT62CO55QQ_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATARVT62CO55QQ_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATARVT62CO55QQ_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATARVT62CO55QQ_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATARVT62CO55QQ_40: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
DATARVT62CO55QQ_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATARVT62CO55QQ_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATARVT62CO55QQ_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATARVT62CO55QQ_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATARVT62CO55QQ_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATARVT62CO55QQ_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATARVT62CO55QQ_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATARVT62CO55QQ_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATARVT62CO55QQ_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATARVT62CO55QQ_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATARVT62CO55QQ_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATARVT62CO55QQ_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATARVT62CO55QQ_4D: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATARVT62CO55QQ_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATARVT62CO55QQ_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATARVT62CO55QQ_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATARVT62CO55QQ_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATARVT62CO55QQ_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATARVT62CO55QQ_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
DATARVT62CO55QQ_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
DATARVT62CO55QQ_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
DATARVT62CO55QQ_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
DATARVT62CO55QQ_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
	even