; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 18 2021 23:08:28 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAG3MTVZ8S6OQ:
	dc.w $0, DATAG3MTVZ8S6OQ_1-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_2-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_3-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_4-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_5-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_6-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_7-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_8-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_9-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_A-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_B-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_C-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_D-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_E-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_F-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_10-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_11-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_12-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_13-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_14-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_15-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_16-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_17-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_18-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_19-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_1A-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_1B-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_1C-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_1D-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_1E-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_1F-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_20-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_21-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_22-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_23-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_24-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_25-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_26-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_27-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_28-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_29-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_2A-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_2B-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_2C-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_2D-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_2E-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_2F-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_30-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_31-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_32-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_33-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_34-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_35-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_36-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_37-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_38-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_39-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_3A-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_3B-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_3C-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_3D-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_3E-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_3F-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_40-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_41-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_42-DATAG3MTVZ8S6OQ, $0
	dc.w $0, DATAG3MTVZ8S6OQ_45-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_46-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_47-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_48-DATAG3MTVZ8S6OQ, $0
	dc.w $0, $0
	dc.w DATAG3MTVZ8S6OQ_4C-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_4D-DATAG3MTVZ8S6OQ
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATAG3MTVZ8S6OQ_53-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_54-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_55-DATAG3MTVZ8S6OQ
	dc.w DATAG3MTVZ8S6OQ_56-DATAG3MTVZ8S6OQ, DATAG3MTVZ8S6OQ_57-DATAG3MTVZ8S6OQ
DATAG3MTVZ8S6OQ_1: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATAG3MTVZ8S6OQ_2: dc.b $2
	dc.b $EC, $F, $0, $0, $F2
	dc.b $C, $C, $0, $10, $F2
DATAG3MTVZ8S6OQ_3: dc.b $2
	dc.b $EC, $F, $0, $0, $F2
	dc.b $C, $C, $0, $10, $F2
DATAG3MTVZ8S6OQ_4: dc.b $2
	dc.b $EC, $F, $0, $0, $F2
	dc.b $C, $C, $0, $10, $F2
DATAG3MTVZ8S6OQ_5: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATAG3MTVZ8S6OQ_6: dc.b $4
	dc.b $ED, $F, $0, $0, $F0
	dc.b $D, $0, $0, $10, $F0
	dc.b $D, $0, $0, $11, $8
	dc.b $FD, $1, $0, $12, $10
DATAG3MTVZ8S6OQ_7: dc.b $2
	dc.b $ED, $F, $0, $0, $F3
	dc.b $D, $C, $0, $10, $F3
DATAG3MTVZ8S6OQ_8: dc.b $2
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F, $4, $0, $C, $F5
DATAG3MTVZ8S6OQ_9: dc.b $3
	dc.b $FA, $E, $0, $0, $EC
	dc.b $EA, $9, $0, $C, $F4
	dc.b $FA, $2, $0, $12, $C
DATAG3MTVZ8S6OQ_A: dc.b $2
	dc.b $FC, $E, $0, $0, $EC
	dc.b $EC, $9, $0, $C, $F4
DATAG3MTVZ8S6OQ_B: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATAG3MTVZ8S6OQ_C: dc.b $4
	dc.b $EE, $E, $0, $0, $ED
	dc.b $6, $4, $0, $C, $F5
	dc.b $E, $1, $0, $E, $FD
	dc.b $EE, $2, $0, $10, $D
DATAG3MTVZ8S6OQ_D: dc.b $3
	dc.b $ED, $E, $0, $0, $EE
	dc.b $5, $9, $0, $C, $F6
	dc.b $F5, $2, $0, $12, $E
DATAG3MTVZ8S6OQ_E: dc.b $3
	dc.b $EC, $A, $0, $0, $EE
	dc.b $4, $D, $0, $9, $F6
	dc.b $FC, $4, $0, $11, $6
DATAG3MTVZ8S6OQ_F: dc.b $4
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $9, $0, $C, $EC
	dc.b $15, $0, $0, $12, $FC
	dc.b $F5, $1, $0, $13, $C
DATAG3MTVZ8S6OQ_10: dc.b $3
	dc.b $EB, $A, $0, $0, $ED
	dc.b $FB, $6, $0, $9, $5
	dc.b $3, $6, $0, $F, $F5
DATAG3MTVZ8S6OQ_11: dc.b $4
	dc.b $EF, $E, $0, $0, $EC
	dc.b $7, $8, $0, $C, $F4
	dc.b $F, $4, $0, $F, $FC
	dc.b $FF, $0, $0, $11, $C
DATAG3MTVZ8S6OQ_12: dc.b $4
	dc.b $F1, $F, $0, $0, $ED
	dc.b $E9, $4, $0, $10, $FD
	dc.b $F1, $0, $0, $12, $D
	dc.b $9, $0, $0, $13, $D
DATAG3MTVZ8S6OQ_13: dc.b $2
	dc.b $EC, $B, $0, $0, $FD
	dc.b $F4, $6, $0, $C, $ED
DATAG3MTVZ8S6OQ_14: dc.b $2
	dc.b $F4, $E, $0, $0, $EF
	dc.b $FC, $1, $0, $C, $F
DATAG3MTVZ8S6OQ_15: dc.b $3
	dc.b $EA, $7, $0, $0, $0
	dc.b $F2, $A, $0, $8, $E8
	dc.b $A, $C, $0, $11, $F8
DATAG3MTVZ8S6OQ_16: dc.b $3
	dc.b $F4, $E, $0, $0, $EE
	dc.b $C, $4, $0, $C, $FE
	dc.b $F4, $1, $0, $E, $E
DATAG3MTVZ8S6OQ_17: dc.b $2
	dc.b $EF, $F, $0, $0, $EF
	dc.b $EF, $3, $0, $10, $F
DATAG3MTVZ8S6OQ_18: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $C, $8, $0, $C, $EC
	dc.b $FC, $8, $0, $F, $4
	dc.b $4, $0, $0, $12, $4
DATAG3MTVZ8S6OQ_19: dc.b $4
	dc.b $F3, $E, $0, $0, $EF
	dc.b $B, $8, $0, $C, $EF
	dc.b $EB, $8, $0, $F, $F7
	dc.b $F3, $0, $0, $12, $F
DATAG3MTVZ8S6OQ_1A: dc.b $3
	dc.b $ED, $A, $0, $0, $FD
	dc.b $F5, $7, $0, $9, $ED
	dc.b $5, $4, $0, $11, $FD
DATAG3MTVZ8S6OQ_1B: dc.b $4
	dc.b $F3, $B, $0, $0, $EC
	dc.b $EB, $4, $0, $C, $F4
	dc.b $FB, $6, $0, $E, $4
	dc.b $FB, $0, $0, $14, $14
DATAG3MTVZ8S6OQ_1C: dc.b $3
	dc.b $FA, $A, $0, $0, $EA
	dc.b $EA, $9, $0, $9, $FA
	dc.b $FA, $9, $0, $F, $2
DATAG3MTVZ8S6OQ_1D: dc.b $4
	dc.b $F4, $E, $0, $0, $ED
	dc.b $C, $8, $0, $C, $ED
	dc.b $EC, $0, $0, $F, $FD
	dc.b $F4, $1, $0, $10, $D
DATAG3MTVZ8S6OQ_1E: dc.b $2
	dc.b $FC, $E, $0, $0, $ED
	dc.b $EC, $9, $0, $C, $F5
DATAG3MTVZ8S6OQ_1F: dc.b $2
	dc.b $FC, $E, $0, $0, $ED
	dc.b $EC, $9, $0, $C, $F5
DATAG3MTVZ8S6OQ_20: dc.b $2
	dc.b $FC, $E, $0, $0, $EC
	dc.b $EC, $9, $0, $C, $F4
DATAG3MTVZ8S6OQ_21: dc.b $2
	dc.b $FC, $E, $0, $0, $ED
	dc.b $EC, $9, $0, $C, $F5
DATAG3MTVZ8S6OQ_22: dc.b $3
	dc.b $EC, $D, $0, $0, $EC
	dc.b $FC, $A, $0, $8, $F4
	dc.b $F4, $2, $0, $11, $C
DATAG3MTVZ8S6OQ_23: dc.b $3
	dc.b $EB, $D, $0, $0, $ED
	dc.b $FB, $A, $0, $8, $F5
	dc.b $FB, $1, $0, $11, $D
DATAG3MTVZ8S6OQ_24: dc.b $3
	dc.b $EC, $D, $0, $0, $EC
	dc.b $FC, $A, $0, $8, $F4
	dc.b $F4, $2, $0, $11, $C
DATAG3MTVZ8S6OQ_25: dc.b $2
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $E, $0, $8, $F4
DATAG3MTVZ8S6OQ_26: dc.b $2
	dc.b $EE, $7, $0, $0, $F1
	dc.b $F6, $B, $0, $8, $1
DATAG3MTVZ8S6OQ_27: dc.b $3
	dc.b $F4, $E, $0, $0, $F0
	dc.b $C, $4, $0, $C, $0
	dc.b $F4, $2, $0, $E, $10
DATAG3MTVZ8S6OQ_28: dc.b $2
	dc.b $EE, $7, $0, $0, $F1
	dc.b $F6, $B, $0, $8, $1
DATAG3MTVZ8S6OQ_29: dc.b $3
	dc.b $F4, $E, $0, $0, $F0
	dc.b $C, $4, $0, $C, $0
	dc.b $F4, $2, $0, $E, $10
DATAG3MTVZ8S6OQ_2A: dc.b $3
	dc.b $EF, $F, $0, $0, $F5
	dc.b $F7, $2, $0, $10, $ED
	dc.b $F, $0, $0, $13, $F5
DATAG3MTVZ8S6OQ_2B: dc.b $3
	dc.b $EC, $7, $0, $0, $FC
	dc.b $F4, $7, $0, $8, $EC
	dc.b $F4, $2, $0, $10, $C
DATAG3MTVZ8S6OQ_2C: dc.b $3
	dc.b $EE, $F, $0, $0, $F5
	dc.b $F6, $2, $0, $10, $ED
	dc.b $E, $0, $0, $13, $F5
DATAG3MTVZ8S6OQ_2D: dc.b $2
	dc.b $ED, $B, $0, $0, $FC
	dc.b $F5, $7, $0, $C, $EC
DATAG3MTVZ8S6OQ_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAG3MTVZ8S6OQ_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAG3MTVZ8S6OQ_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAG3MTVZ8S6OQ_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAG3MTVZ8S6OQ_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAG3MTVZ8S6OQ_33: dc.b $2
	dc.b $F5, $E, $0, $0, $EC
	dc.b $F5, $2, $0, $C, $C
DATAG3MTVZ8S6OQ_34: dc.b $3
	dc.b $F8, $A, $0, $0, $F0
	dc.b $F0, $8, $0, $9, $F8
	dc.b $F8, $1, $0, $C, $8
DATAG3MTVZ8S6OQ_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
DATAG3MTVZ8S6OQ_36: dc.b $3
	dc.b $F0, $A, $0, $0, $F0
	dc.b $8, $8, $0, $9, $F8
	dc.b $F8, $1, $0, $C, $8
DATAG3MTVZ8S6OQ_37: dc.b $3
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $4, $0, $C, $0
	dc.b $FD, $1, $0, $E, $8
DATAG3MTVZ8S6OQ_38: dc.b $3
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $4, $0, $C, $0
	dc.b $FD, $1, $0, $E, $8
DATAG3MTVZ8S6OQ_39: dc.b $2
	dc.b $EE, $B, $0, $0, $F2
	dc.b $E, $C, $0, $C, $F2
DATAG3MTVZ8S6OQ_3A: dc.b $2
	dc.b $EF, $F, $0, $0, $E6
	dc.b $F, $4, $0, $10, $EE
DATAG3MTVZ8S6OQ_3B: dc.b $2
	dc.b $EC, $E, $0, $0, $E5
	dc.b $4, $9, $0, $C, $ED
DATAG3MTVZ8S6OQ_3C: dc.b $2
	dc.b $F4, $E, $0, $0, $FC
	dc.b $FC, $5, $0, $C, $EC
DATAG3MTVZ8S6OQ_3D: dc.b $3
	dc.b $F4, $D, $0, $0, $E8
	dc.b $4, $C, $0, $8, $F0
	dc.b $F4, $5, $0, $C, $8
DATAG3MTVZ8S6OQ_3E: dc.b $2
	dc.b $F4, $E, $0, $0, $E4
	dc.b $FC, $1, $0, $C, $4
DATAG3MTVZ8S6OQ_3F: dc.b $2
	dc.b $F4, $E, $0, $0, $FC
	dc.b $FC, $5, $0, $C, $EC
DATAG3MTVZ8S6OQ_40: dc.b $2
	dc.b $EB, $B, $0, $0, $F0
	dc.b $B, $5, $0, $C, $F0
DATAG3MTVZ8S6OQ_41: dc.b $3
	dc.b $F6, $E, $0, $0, $E8
	dc.b $F6, $3, $0, $C, $8
	dc.b $FE, $2, $0, $10, $10
DATAG3MTVZ8S6OQ_42: dc.b $3
	dc.b $F6, $E, $0, $0, $E8
	dc.b $F6, $3, $0, $C, $8
	dc.b $FE, $2, $0, $10, $10
DATAG3MTVZ8S6OQ_45: dc.b $2
	dc.b $8, $D, $0, $0, $EB
	dc.b $F0, $A, $0, $8, $F3
DATAG3MTVZ8S6OQ_46: dc.b $2
	dc.b $EF, $B, $0, $0, $F3
	dc.b $F, $4, $0, $C, $F3
DATAG3MTVZ8S6OQ_47: dc.b $2
	dc.b $8, $D, $0, $0, $EB
	dc.b $F0, $A, $0, $8, $F3
DATAG3MTVZ8S6OQ_48: dc.b $2
	dc.b $EF, $B, $0, $0, $F3
	dc.b $F, $4, $0, $C, $F3
DATAG3MTVZ8S6OQ_4C: dc.b $3
	dc.b $E7, $E, $0, $0, $EF
	dc.b $FF, $A, $0, $C, $F7
	dc.b $E7, $1, $0, $15, $F
DATAG3MTVZ8S6OQ_4D: dc.b $3
	dc.b $E8, $D, $0, $0, $EB
	dc.b $F8, $B, $0, $8, $F3
	dc.b $E8, $1, $0, $14, $B
DATAG3MTVZ8S6OQ_53: dc.b $2
	dc.b $F4, $E, $8, $0, $E4
	dc.b $FC, $5, $8, $C, $4
DATAG3MTVZ8S6OQ_54: dc.b $2
	dc.b $F4, $E, $8, $0, $FB
	dc.b $FC, $1, $8, $C, $F3
DATAG3MTVZ8S6OQ_55: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $D, $8, $0, $C, $FC
	dc.b $F5, $2, $0, $F, $C
DATAG3MTVZ8S6OQ_56: dc.b $3
	dc.b $FA, $E, $0, $0, $EC
	dc.b $EA, $9, $0, $C, $F4
	dc.b $2, $1, $0, $12, $C
DATAG3MTVZ8S6OQ_57: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $D, $8, $0, $C, $FC
	dc.b $F5, $2, $0, $F, $C
	even