; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Aug 23 2021 19:36:07 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA1J1ZI1I6W6R:
	dc.w $0, DATA1J1ZI1I6W6R_1-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_2-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_3-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_4-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_5-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_6-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_7-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_8-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_9-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_A-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_B-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_C-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_D-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_E-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_F-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_10-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_11-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_12-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_13-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_14-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_15-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_16-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_17-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_18-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_19-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_1A-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_1B-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_1C-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_1D-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_1E-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_1F-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_20-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_21-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_22-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_23-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_24-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_25-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_26-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_27-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_28-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_29-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_2A-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_2B-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_2C-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_2D-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_2E-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_2F-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_30-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_31-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_32-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_33-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_34-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_35-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_36-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_37-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_38-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_39-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_3A-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_3B-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_3C-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_3D-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_3E-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_3F-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_40-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_41-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_42-DATA1J1ZI1I6W6R, $0
	dc.w $0, DATA1J1ZI1I6W6R_45-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_46-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_47-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_48-DATA1J1ZI1I6W6R, $0
	dc.w $0, $0
	dc.w DATA1J1ZI1I6W6R_4C-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_4D-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_4E-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_4F-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_50-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_51-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_52-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_53-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_54-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_55-DATA1J1ZI1I6W6R
	dc.w DATA1J1ZI1I6W6R_56-DATA1J1ZI1I6W6R, DATA1J1ZI1I6W6R_57-DATA1J1ZI1I6W6R
DATA1J1ZI1I6W6R_1: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATA1J1ZI1I6W6R_2: dc.b $2
	dc.b $EC, $F, $0, $0, $F2
	dc.b $C, $C, $0, $10, $F2
DATA1J1ZI1I6W6R_3: dc.b $2
	dc.b $EC, $F, $0, $0, $F2
	dc.b $C, $C, $0, $10, $F2
DATA1J1ZI1I6W6R_4: dc.b $2
	dc.b $EC, $F, $0, $0, $F2
	dc.b $C, $C, $0, $10, $F2
DATA1J1ZI1I6W6R_5: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATA1J1ZI1I6W6R_6: dc.b $4
	dc.b $ED, $F, $0, $0, $F0
	dc.b $D, $0, $0, $10, $F0
	dc.b $D, $0, $0, $11, $8
	dc.b $FD, $1, $0, $12, $10
DATA1J1ZI1I6W6R_7: dc.b $2
	dc.b $ED, $F, $0, $0, $F3
	dc.b $D, $C, $0, $10, $F3
DATA1J1ZI1I6W6R_8: dc.b $2
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F, $4, $0, $C, $F5
DATA1J1ZI1I6W6R_9: dc.b $3
	dc.b $FA, $E, $0, $0, $EC
	dc.b $EA, $9, $0, $C, $F4
	dc.b $FA, $2, $0, $12, $C
DATA1J1ZI1I6W6R_A: dc.b $2
	dc.b $FC, $E, $0, $0, $EC
	dc.b $EC, $9, $0, $C, $F4
DATA1J1ZI1I6W6R_B: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATA1J1ZI1I6W6R_C: dc.b $4
	dc.b $EE, $E, $0, $0, $ED
	dc.b $6, $4, $0, $C, $F5
	dc.b $E, $1, $0, $E, $FD
	dc.b $EE, $2, $0, $10, $D
DATA1J1ZI1I6W6R_D: dc.b $3
	dc.b $ED, $E, $0, $0, $EE
	dc.b $5, $9, $0, $C, $F6
	dc.b $F5, $2, $0, $12, $E
DATA1J1ZI1I6W6R_E: dc.b $3
	dc.b $EC, $A, $0, $0, $EE
	dc.b $4, $D, $0, $9, $F6
	dc.b $FC, $4, $0, $11, $6
DATA1J1ZI1I6W6R_F: dc.b $4
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $9, $0, $C, $EC
	dc.b $15, $0, $0, $12, $FC
	dc.b $F5, $1, $0, $13, $C
DATA1J1ZI1I6W6R_10: dc.b $3
	dc.b $EB, $A, $0, $0, $ED
	dc.b $FB, $6, $0, $9, $5
	dc.b $3, $6, $0, $F, $F5
DATA1J1ZI1I6W6R_11: dc.b $4
	dc.b $EF, $E, $0, $0, $EC
	dc.b $7, $8, $0, $C, $F4
	dc.b $F, $4, $0, $F, $FC
	dc.b $FF, $0, $0, $11, $C
DATA1J1ZI1I6W6R_12: dc.b $4
	dc.b $F1, $F, $0, $0, $ED
	dc.b $E9, $4, $0, $10, $FD
	dc.b $F1, $0, $0, $12, $D
	dc.b $9, $0, $0, $13, $D
DATA1J1ZI1I6W6R_13: dc.b $2
	dc.b $EC, $B, $0, $0, $FD
	dc.b $F4, $6, $0, $C, $ED
DATA1J1ZI1I6W6R_14: dc.b $2
	dc.b $F4, $E, $0, $0, $EF
	dc.b $FC, $1, $0, $C, $F
DATA1J1ZI1I6W6R_15: dc.b $3
	dc.b $EA, $7, $0, $0, $0
	dc.b $F2, $A, $0, $8, $E8
	dc.b $A, $C, $0, $11, $F8
DATA1J1ZI1I6W6R_16: dc.b $3
	dc.b $F4, $E, $0, $0, $EE
	dc.b $C, $4, $0, $C, $FE
	dc.b $F4, $1, $0, $E, $E
DATA1J1ZI1I6W6R_17: dc.b $2
	dc.b $EF, $F, $0, $0, $EF
	dc.b $EF, $3, $0, $10, $F
DATA1J1ZI1I6W6R_18: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $C, $8, $0, $C, $EC
	dc.b $FC, $8, $0, $F, $4
	dc.b $4, $0, $0, $12, $4
DATA1J1ZI1I6W6R_19: dc.b $4
	dc.b $F3, $E, $0, $0, $EF
	dc.b $B, $8, $0, $C, $EF
	dc.b $EB, $8, $0, $F, $F7
	dc.b $F3, $0, $0, $12, $F
DATA1J1ZI1I6W6R_1A: dc.b $3
	dc.b $ED, $A, $0, $0, $FD
	dc.b $F5, $7, $0, $9, $ED
	dc.b $5, $4, $0, $11, $FD
DATA1J1ZI1I6W6R_1B: dc.b $4
	dc.b $F3, $B, $0, $0, $EC
	dc.b $EB, $4, $0, $C, $F4
	dc.b $FB, $6, $0, $E, $4
	dc.b $FB, $0, $0, $14, $14
DATA1J1ZI1I6W6R_1C: dc.b $3
	dc.b $FA, $A, $0, $0, $EA
	dc.b $EA, $9, $0, $9, $FA
	dc.b $FA, $9, $0, $F, $2
DATA1J1ZI1I6W6R_1D: dc.b $4
	dc.b $F4, $E, $0, $0, $ED
	dc.b $C, $8, $0, $C, $ED
	dc.b $EC, $0, $0, $F, $FD
	dc.b $F4, $1, $0, $10, $D
DATA1J1ZI1I6W6R_1E: dc.b $2
	dc.b $FC, $E, $0, $0, $ED
	dc.b $EC, $9, $0, $C, $F5
DATA1J1ZI1I6W6R_1F: dc.b $2
	dc.b $FC, $E, $0, $0, $ED
	dc.b $EC, $9, $0, $C, $F5
DATA1J1ZI1I6W6R_20: dc.b $2
	dc.b $FC, $E, $0, $0, $EC
	dc.b $EC, $9, $0, $C, $F4
DATA1J1ZI1I6W6R_21: dc.b $2
	dc.b $FC, $E, $0, $0, $ED
	dc.b $EC, $9, $0, $C, $F5
DATA1J1ZI1I6W6R_22: dc.b $3
	dc.b $EC, $D, $0, $0, $EC
	dc.b $FC, $A, $0, $8, $F4
	dc.b $F4, $2, $0, $11, $C
DATA1J1ZI1I6W6R_23: dc.b $3
	dc.b $EB, $D, $0, $0, $ED
	dc.b $FB, $A, $0, $8, $F5
	dc.b $FB, $1, $0, $11, $D
DATA1J1ZI1I6W6R_24: dc.b $3
	dc.b $EC, $D, $0, $0, $EC
	dc.b $FC, $A, $0, $8, $F4
	dc.b $F4, $2, $0, $11, $C
DATA1J1ZI1I6W6R_25: dc.b $2
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $E, $0, $8, $F4
DATA1J1ZI1I6W6R_26: dc.b $2
	dc.b $EE, $7, $0, $0, $F1
	dc.b $F6, $B, $0, $8, $1
DATA1J1ZI1I6W6R_27: dc.b $3
	dc.b $F4, $E, $0, $0, $F0
	dc.b $C, $4, $0, $C, $0
	dc.b $F4, $2, $0, $E, $10
DATA1J1ZI1I6W6R_28: dc.b $2
	dc.b $EE, $7, $0, $0, $F1
	dc.b $F6, $B, $0, $8, $1
DATA1J1ZI1I6W6R_29: dc.b $3
	dc.b $F4, $E, $0, $0, $F0
	dc.b $C, $4, $0, $C, $0
	dc.b $F4, $2, $0, $E, $10
DATA1J1ZI1I6W6R_2A: dc.b $3
	dc.b $EF, $F, $0, $0, $F5
	dc.b $F7, $2, $0, $10, $ED
	dc.b $F, $0, $0, $13, $F5
DATA1J1ZI1I6W6R_2B: dc.b $3
	dc.b $EC, $7, $0, $0, $FC
	dc.b $F4, $7, $0, $8, $EC
	dc.b $F4, $2, $0, $10, $C
DATA1J1ZI1I6W6R_2C: dc.b $3
	dc.b $EE, $F, $0, $0, $F5
	dc.b $F6, $2, $0, $10, $ED
	dc.b $E, $0, $0, $13, $F5
DATA1J1ZI1I6W6R_2D: dc.b $2
	dc.b $ED, $B, $0, $0, $FC
	dc.b $F5, $7, $0, $C, $EC
DATA1J1ZI1I6W6R_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA1J1ZI1I6W6R_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA1J1ZI1I6W6R_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA1J1ZI1I6W6R_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA1J1ZI1I6W6R_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA1J1ZI1I6W6R_33: dc.b $2
	dc.b $F5, $E, $0, $0, $EC
	dc.b $F5, $2, $0, $C, $C
DATA1J1ZI1I6W6R_34: dc.b $3
	dc.b $F8, $A, $0, $0, $F0
	dc.b $F0, $8, $0, $9, $F8
	dc.b $F8, $1, $0, $C, $8
DATA1J1ZI1I6W6R_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
DATA1J1ZI1I6W6R_36: dc.b $3
	dc.b $F0, $A, $0, $0, $F0
	dc.b $8, $8, $0, $9, $F8
	dc.b $F8, $1, $0, $C, $8
DATA1J1ZI1I6W6R_37: dc.b $3
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $4, $0, $C, $0
	dc.b $FD, $1, $0, $E, $8
DATA1J1ZI1I6W6R_38: dc.b $3
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $4, $0, $C, $0
	dc.b $FD, $1, $0, $E, $8
DATA1J1ZI1I6W6R_39: dc.b $2
	dc.b $EE, $B, $0, $0, $F2
	dc.b $E, $C, $0, $C, $F2
DATA1J1ZI1I6W6R_3A: dc.b $2
	dc.b $EF, $F, $0, $0, $E6
	dc.b $F, $4, $0, $10, $EE
DATA1J1ZI1I6W6R_3B: dc.b $2
	dc.b $EC, $E, $0, $0, $E5
	dc.b $4, $9, $0, $C, $ED
DATA1J1ZI1I6W6R_3C: dc.b $2
	dc.b $F4, $E, $0, $0, $FC
	dc.b $FC, $5, $0, $C, $EC
DATA1J1ZI1I6W6R_3D: dc.b $3
	dc.b $F4, $D, $0, $0, $E8
	dc.b $4, $C, $0, $8, $F0
	dc.b $F4, $5, $0, $C, $8
DATA1J1ZI1I6W6R_3E: dc.b $2
	dc.b $F4, $E, $0, $0, $E4
	dc.b $FC, $1, $0, $C, $4
DATA1J1ZI1I6W6R_3F: dc.b $2
	dc.b $F4, $E, $0, $0, $FC
	dc.b $FC, $5, $0, $C, $EC
DATA1J1ZI1I6W6R_40: dc.b $2
	dc.b $EB, $B, $0, $0, $F0
	dc.b $B, $5, $0, $C, $F0
DATA1J1ZI1I6W6R_41: dc.b $3
	dc.b $F6, $E, $0, $0, $E8
	dc.b $F6, $3, $0, $C, $8
	dc.b $FE, $2, $0, $10, $10
DATA1J1ZI1I6W6R_42: dc.b $3
	dc.b $F6, $E, $0, $0, $E8
	dc.b $F6, $3, $0, $C, $8
	dc.b $FE, $2, $0, $10, $10
DATA1J1ZI1I6W6R_45: dc.b $2
	dc.b $8, $D, $0, $0, $EB
	dc.b $F0, $A, $0, $8, $F3
DATA1J1ZI1I6W6R_46: dc.b $2
	dc.b $EF, $B, $0, $0, $F3
	dc.b $F, $4, $0, $C, $F3
DATA1J1ZI1I6W6R_47: dc.b $2
	dc.b $8, $D, $0, $0, $EB
	dc.b $F0, $A, $0, $8, $F3
DATA1J1ZI1I6W6R_48: dc.b $2
	dc.b $EF, $B, $0, $0, $F3
	dc.b $F, $4, $0, $C, $F3
DATA1J1ZI1I6W6R_4C: dc.b $3
	dc.b $E7, $E, $0, $0, $EF
	dc.b $FF, $A, $0, $C, $F7
	dc.b $E7, $1, $0, $15, $F
DATA1J1ZI1I6W6R_4D: dc.b $3
	dc.b $E8, $D, $0, $0, $EB
	dc.b $F8, $B, $0, $8, $F3
	dc.b $E8, $1, $0, $14, $B
DATA1J1ZI1I6W6R_4E: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $C, $0, $C, $F0
	dc.b $F4, $2, $0, $10, $8
DATA1J1ZI1I6W6R_4F: dc.b $2
	dc.b $ED, $E, $0, $0, $EF
	dc.b $5, $9, $0, $C, $F7
DATA1J1ZI1I6W6R_50: dc.b $1
	dc.b $F1, $B, $0, $0, $F3
DATA1J1ZI1I6W6R_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATA1J1ZI1I6W6R_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATA1J1ZI1I6W6R_53: dc.b $2
	dc.b $F4, $E, $8, $0, $E4
	dc.b $FC, $5, $8, $C, $4
DATA1J1ZI1I6W6R_54: dc.b $2
	dc.b $F4, $E, $8, $0, $FB
	dc.b $FC, $1, $8, $C, $F3
DATA1J1ZI1I6W6R_55: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $D, $8, $0, $C, $FC
	dc.b $F5, $2, $0, $F, $C
DATA1J1ZI1I6W6R_56: dc.b $3
	dc.b $FA, $E, $0, $0, $EC
	dc.b $EA, $9, $0, $C, $F4
	dc.b $2, $1, $0, $12, $C
DATA1J1ZI1I6W6R_57: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $D, $8, $0, $C, $FC
	dc.b $F5, $2, $0, $F, $C
	even