; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 18 2021 22:49:53 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAM6X5ZCVT14H:
	dc.w $0, DATAM6X5ZCVT14H_1-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_2-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_3-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_4-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_5-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_6-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_7-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_8-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_9-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_A-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_B-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_C-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_D-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_E-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_F-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_10-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_11-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_12-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_13-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_14-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_15-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_16-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_17-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_18-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_19-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_1A-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_1B-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_1C-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_1D-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_1E-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_1F-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_20-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_21-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_22-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_23-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_24-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_25-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_26-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_27-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_28-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_29-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_2A-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_2B-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_2C-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_2D-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_2E-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_2F-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_30-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_31-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_32-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_33-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_34-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_35-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_36-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_37-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_38-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_39-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_3A-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_3B-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_3C-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_3D-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_3E-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_3F-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_40-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_41-DATAM6X5ZCVT14H
	dc.w $0, $0
	dc.w DATAM6X5ZCVT14H_44-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_45-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_46-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_47-DATAM6X5ZCVT14H
	dc.w $0, $0
	dc.w $0, DATAM6X5ZCVT14H_4B-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_4C-DATAM6X5ZCVT14H, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w DATAM6X5ZCVT14H_52-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_53-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_54-DATAM6X5ZCVT14H, DATAM6X5ZCVT14H_55-DATAM6X5ZCVT14H
	dc.w DATAM6X5ZCVT14H_56-DATAM6X5ZCVT14H
DATAM6X5ZCVT14H_1: dc.b $2
	dc.b $EE, $F, $0, $0, $F0
	dc.b $E, $C, $0, $10, $F0
DATAM6X5ZCVT14H_2: dc.b $2
	dc.b $EB, $F, $0, $0, $F2
	dc.b $B, $C, $0, $10, $F2
DATAM6X5ZCVT14H_3: dc.b $2
	dc.b $EB, $F, $0, $0, $F2
	dc.b $B, $C, $0, $10, $F2
DATAM6X5ZCVT14H_4: dc.b $2
	dc.b $EB, $F, $0, $0, $F2
	dc.b $B, $C, $0, $10, $F2
DATAM6X5ZCVT14H_5: dc.b $2
	dc.b $EE, $F, $0, $0, $F0
	dc.b $E, $C, $0, $10, $F0
DATAM6X5ZCVT14H_6: dc.b $4
	dc.b $ED, $F, $0, $0, $F0
	dc.b $D, $0, $0, $10, $F0
	dc.b $D, $0, $0, $11, $8
	dc.b $FD, $1, $0, $12, $10
DATAM6X5ZCVT14H_7: dc.b $2
	dc.b $ED, $F, $0, $0, $F3
	dc.b $D, $C, $0, $10, $F3
DATAM6X5ZCVT14H_8: dc.b $2
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F, $4, $0, $C, $F5
DATAM6X5ZCVT14H_9: dc.b $3
	dc.b $FA, $E, $0, $0, $EC
	dc.b $EA, $9, $0, $C, $F4
	dc.b $FA, $2, $0, $12, $C
DATAM6X5ZCVT14H_A: dc.b $2
	dc.b $FC, $E, $0, $0, $EC
	dc.b $EC, $9, $0, $C, $F4
DATAM6X5ZCVT14H_B: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATAM6X5ZCVT14H_C: dc.b $4
	dc.b $EE, $E, $0, $0, $ED
	dc.b $6, $4, $0, $C, $F5
	dc.b $E, $1, $0, $E, $FD
	dc.b $EE, $2, $0, $10, $D
DATAM6X5ZCVT14H_D: dc.b $3
	dc.b $ED, $E, $0, $0, $EE
	dc.b $5, $9, $0, $C, $F6
	dc.b $F5, $2, $0, $12, $E
DATAM6X5ZCVT14H_E: dc.b $3
	dc.b $EC, $A, $0, $0, $EE
	dc.b $4, $D, $0, $9, $F6
	dc.b $FC, $4, $0, $11, $6
DATAM6X5ZCVT14H_F: dc.b $4
	dc.b $ED, $E, $0, $0, $EC
	dc.b $5, $9, $0, $C, $EC
	dc.b $15, $0, $0, $12, $FC
	dc.b $F5, $1, $0, $13, $C
DATAM6X5ZCVT14H_10: dc.b $3
	dc.b $EB, $A, $0, $0, $ED
	dc.b $FB, $6, $0, $9, $5
	dc.b $3, $6, $0, $F, $F5
DATAM6X5ZCVT14H_11: dc.b $4
	dc.b $EF, $E, $0, $0, $EC
	dc.b $7, $8, $0, $C, $F4
	dc.b $F, $4, $0, $F, $FC
	dc.b $FF, $0, $0, $11, $C
DATAM6X5ZCVT14H_12: dc.b $4
	dc.b $F1, $F, $0, $0, $ED
	dc.b $E9, $4, $0, $10, $FD
	dc.b $F1, $0, $0, $12, $D
	dc.b $9, $0, $0, $13, $D
DATAM6X5ZCVT14H_13: dc.b $2
	dc.b $EC, $B, $0, $0, $FD
	dc.b $F4, $6, $0, $C, $ED
DATAM6X5ZCVT14H_14: dc.b $2
	dc.b $F4, $E, $0, $0, $EF
	dc.b $FC, $1, $0, $C, $F
DATAM6X5ZCVT14H_15: dc.b $3
	dc.b $EA, $7, $0, $0, $0
	dc.b $F2, $A, $0, $8, $E8
	dc.b $A, $C, $0, $11, $F8
DATAM6X5ZCVT14H_16: dc.b $3
	dc.b $F4, $E, $0, $0, $EE
	dc.b $C, $4, $0, $C, $FE
	dc.b $F4, $1, $0, $E, $E
DATAM6X5ZCVT14H_17: dc.b $2
	dc.b $EF, $F, $0, $0, $EF
	dc.b $EF, $3, $0, $10, $F
DATAM6X5ZCVT14H_18: dc.b $4
	dc.b $EC, $B, $0, $0, $EC
	dc.b $C, $8, $0, $C, $EC
	dc.b $FC, $8, $0, $F, $4
	dc.b $4, $0, $0, $12, $4
DATAM6X5ZCVT14H_19: dc.b $4
	dc.b $F3, $E, $0, $0, $EF
	dc.b $B, $8, $0, $C, $EF
	dc.b $EB, $8, $0, $F, $F7
	dc.b $F3, $0, $0, $12, $F
DATAM6X5ZCVT14H_1A: dc.b $3
	dc.b $ED, $A, $0, $0, $FD
	dc.b $F5, $7, $0, $9, $ED
	dc.b $5, $4, $0, $11, $FD
DATAM6X5ZCVT14H_1B: dc.b $4
	dc.b $F3, $B, $0, $0, $EC
	dc.b $EB, $4, $0, $C, $F4
	dc.b $FB, $6, $0, $E, $4
	dc.b $FB, $0, $0, $14, $14
DATAM6X5ZCVT14H_1C: dc.b $3
	dc.b $FA, $A, $0, $0, $EA
	dc.b $EA, $9, $0, $9, $FA
	dc.b $FA, $9, $0, $F, $2
DATAM6X5ZCVT14H_1D: dc.b $4
	dc.b $F4, $E, $0, $0, $ED
	dc.b $C, $8, $0, $C, $ED
	dc.b $EC, $0, $0, $F, $FD
	dc.b $F4, $1, $0, $10, $D
DATAM6X5ZCVT14H_1E: dc.b $2
	dc.b $FC, $E, $0, $0, $ED
	dc.b $EC, $9, $0, $C, $F5
DATAM6X5ZCVT14H_1F: dc.b $2
	dc.b $FC, $E, $0, $0, $ED
	dc.b $EC, $9, $0, $C, $F5
DATAM6X5ZCVT14H_20: dc.b $2
	dc.b $FC, $E, $0, $0, $EC
	dc.b $EC, $9, $0, $C, $F4
DATAM6X5ZCVT14H_21: dc.b $2
	dc.b $FC, $E, $0, $0, $ED
	dc.b $EC, $9, $0, $C, $F5
DATAM6X5ZCVT14H_22: dc.b $3
	dc.b $EC, $D, $0, $0, $EC
	dc.b $FC, $A, $0, $8, $F4
	dc.b $F4, $2, $0, $11, $C
DATAM6X5ZCVT14H_23: dc.b $3
	dc.b $EB, $D, $0, $0, $ED
	dc.b $FB, $A, $0, $8, $F5
	dc.b $FB, $1, $0, $11, $D
DATAM6X5ZCVT14H_24: dc.b $3
	dc.b $EC, $D, $0, $0, $EC
	dc.b $FC, $A, $0, $8, $F4
	dc.b $F4, $2, $0, $11, $C
DATAM6X5ZCVT14H_25: dc.b $2
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $E, $0, $8, $F4
DATAM6X5ZCVT14H_26: dc.b $2
	dc.b $EE, $7, $0, $0, $F1
	dc.b $F6, $B, $0, $8, $1
DATAM6X5ZCVT14H_27: dc.b $3
	dc.b $F4, $E, $0, $0, $F0
	dc.b $C, $4, $0, $C, $0
	dc.b $F4, $2, $0, $E, $10
DATAM6X5ZCVT14H_28: dc.b $2
	dc.b $EE, $7, $0, $0, $F1
	dc.b $F6, $B, $0, $8, $1
DATAM6X5ZCVT14H_29: dc.b $3
	dc.b $F4, $E, $0, $0, $F0
	dc.b $C, $4, $0, $C, $0
	dc.b $F4, $2, $0, $E, $10
DATAM6X5ZCVT14H_2A: dc.b $3
	dc.b $EF, $F, $0, $0, $F5
	dc.b $F7, $2, $0, $10, $ED
	dc.b $F, $0, $0, $13, $F5
DATAM6X5ZCVT14H_2B: dc.b $3
	dc.b $EC, $7, $0, $0, $FC
	dc.b $F4, $7, $0, $8, $EC
	dc.b $F4, $2, $0, $10, $C
DATAM6X5ZCVT14H_2C: dc.b $3
	dc.b $EE, $F, $0, $0, $F5
	dc.b $F6, $2, $0, $10, $ED
	dc.b $E, $0, $0, $13, $F5
DATAM6X5ZCVT14H_2D: dc.b $2
	dc.b $ED, $B, $0, $0, $FC
	dc.b $F5, $7, $0, $C, $EC
DATAM6X5ZCVT14H_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM6X5ZCVT14H_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM6X5ZCVT14H_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM6X5ZCVT14H_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM6X5ZCVT14H_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAM6X5ZCVT14H_33: dc.b $2
	dc.b $F5, $E, $0, $0, $EC
	dc.b $F5, $2, $0, $C, $C
DATAM6X5ZCVT14H_34: dc.b $3
	dc.b $F8, $A, $0, $0, $F0
	dc.b $F0, $8, $0, $9, $F8
	dc.b $F8, $1, $0, $C, $8
DATAM6X5ZCVT14H_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
DATAM6X5ZCVT14H_36: dc.b $3
	dc.b $F0, $A, $0, $0, $F0
	dc.b $8, $8, $0, $9, $F8
	dc.b $F8, $1, $0, $C, $8
DATAM6X5ZCVT14H_37: dc.b $3
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $4, $0, $C, $0
	dc.b $FD, $1, $0, $E, $8
DATAM6X5ZCVT14H_38: dc.b $3
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $4, $0, $C, $0
	dc.b $FD, $1, $0, $E, $8
DATAM6X5ZCVT14H_39: dc.b $2
	dc.b $EE, $B, $0, $0, $F2
	dc.b $E, $C, $0, $C, $F2
DATAM6X5ZCVT14H_3A: dc.b $2
	dc.b $EF, $F, $0, $0, $E6
	dc.b $F, $4, $0, $10, $EE
DATAM6X5ZCVT14H_3B: dc.b $2
	dc.b $EC, $E, $0, $0, $E5
	dc.b $4, $9, $0, $C, $ED
DATAM6X5ZCVT14H_3C: dc.b $2
	dc.b $F4, $E, $0, $0, $FC
	dc.b $FC, $5, $0, $C, $EC
DATAM6X5ZCVT14H_3D: dc.b $3
	dc.b $F4, $D, $0, $0, $E8
	dc.b $4, $C, $0, $8, $F0
	dc.b $F4, $5, $0, $C, $8
DATAM6X5ZCVT14H_3E: dc.b $2
	dc.b $F4, $E, $0, $0, $E4
	dc.b $FC, $1, $0, $C, $4
DATAM6X5ZCVT14H_3F: dc.b $2
	dc.b $F4, $E, $0, $0, $FC
	dc.b $FC, $5, $0, $C, $EC
DATAM6X5ZCVT14H_40: dc.b $2
	dc.b $EB, $B, $0, $0, $F0
	dc.b $B, $5, $0, $C, $F0
DATAM6X5ZCVT14H_41: dc.b $3
	dc.b $F6, $E, $0, $0, $E8
	dc.b $F6, $3, $0, $C, $8
	dc.b $FE, $2, $0, $10, $10
DATAM6X5ZCVT14H_44: dc.b $2
	dc.b $8, $D, $0, $0, $EB
	dc.b $F0, $A, $0, $8, $F3
DATAM6X5ZCVT14H_45: dc.b $2
	dc.b $EF, $B, $0, $0, $F3
	dc.b $F, $4, $0, $C, $F3
DATAM6X5ZCVT14H_46: dc.b $2
	dc.b $8, $D, $0, $0, $EB
	dc.b $F0, $A, $0, $8, $F3
DATAM6X5ZCVT14H_47: dc.b $2
	dc.b $EF, $B, $0, $0, $F3
	dc.b $F, $4, $0, $C, $F3
DATAM6X5ZCVT14H_4B: dc.b $3
	dc.b $E7, $E, $0, $0, $EF
	dc.b $FF, $A, $0, $C, $F7
	dc.b $E7, $1, $0, $15, $F
DATAM6X5ZCVT14H_4C: dc.b $3
	dc.b $E8, $D, $0, $0, $EB
	dc.b $F8, $B, $0, $8, $F3
	dc.b $E8, $1, $0, $14, $B
DATAM6X5ZCVT14H_52: dc.b $2
	dc.b $F4, $E, $8, $0, $E4
	dc.b $FC, $5, $8, $C, $4
DATAM6X5ZCVT14H_53: dc.b $2
	dc.b $F4, $E, $8, $0, $FB
	dc.b $FC, $1, $8, $C, $F3
DATAM6X5ZCVT14H_54: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $D, $8, $0, $C, $FC
	dc.b $F5, $2, $0, $F, $C
DATAM6X5ZCVT14H_55: dc.b $3
	dc.b $FA, $E, $0, $0, $EC
	dc.b $EA, $9, $0, $C, $F4
	dc.b $2, $1, $0, $12, $C
DATAM6X5ZCVT14H_56: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $D, $8, $0, $C, $FC
	dc.b $F5, $2, $0, $F, $C
	even